### ISSUE TITLE
Dashboard: Dashboard hangs when trying to view logs

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#3083] opened 2016-07-08 14:29 UTC
I was trying to look at the logs for one of our main apps. This apps generates a lot of log entries. This has occurred twice. Here is what I was doing:

- Click on app name from list of apps
- On next screen, from the "Process Logs" list, click one of the "worker" logs
- Nothing happens, and I can't click on any other links
- Eventually Chrome complains about the tab being unresponsivle and asks if I want to kill it.
- Check the output of `flynn -a dashboard log` but don't see any errors

This only appears to be an issue with this one app.

**Comment by jvatic** [comment] 2016-07-11 18:50
Are you able to view the logs for this app via the cli (e.g. `flynn log --process-type=worker`)? Also, do you see any errors in the browser console?

**Comment by tjboring** [comment] 2016-07-11 23:25
Yes, viewing the logs from the CLI works.

Wow, so I just retried this again from the dashboard, and, of course, it's working just fine (even from a slow connection on a Verizon jetpack).  

I'll try to reproduce this issue again over the next couple of days and post more details if I can.

**Comment by jvatic** [comment] 2016-07-26 19:13
Closing due to insufficient information for determining the cause of this issue

**Closed by jvatic** 2016-07-26 19:13 UTC
Labels: bug, dashboard

**Comment by ron137** [comment] 2016-10-14 11:44
I also have this problem.
Its happen because that my app enter into crashing loop, and then the process logs filled with "CRASHED" "DOWN" "CRASHED" "DOWN"...  processes
When I'm trying to access the log of that app the browser become extremely stuck and if I wait 5 minutes it is finish to load and I will able to see the logs, but its take 5-10 minues!

I think that dynamic scroll pagination on process logs list can solve this problem.

**Comment by reneweteling** [comment] 2017-08-14 07:35
Whats the status of this item? Im having teh same issues, and it is is like @rob137 states, when the app has allot of logs by crashed down crashed etc it hangs other apps go as aspected. Id love to add a PR but im a Rails guy... dont know Go (yet)

Thanks for the awesome job!!

**Comment by mfclarke** [comment] 2017-09-04 15:55
I'm also seeing this and opened #4238 because I figure clearing the logs would work around it
