### ISSUE TITLE
Restore / upgrade to 16.04 fails

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3814] opened 2017-01-10 03:25 UTC
https://bazaarvoice.box.com/s/4k9comma4uw4k6uf5va1ys4h6rg9i1rg is debug info from two nodes. The third node was inaccessible entirely. I am retrying now, but I believe I've seen this before.

**Comment by temujin9** [comment] 2017-01-10 21:01
Third node has returned to accessible, and appears to have bootstrapped successfully. However, the cluster does not coalesce, and was unfortunately torn down before I could get fuller debug info from the third node.

Another instance of the cluster built correctly, so this may be lower priority. I will attempt some additional builds against it, once I've made our backups work with the restrictions of 16.04.

**Comment by lmars** [comment] 2017-01-12 01:03
@temujin9 it looks like the third node became inaccessible at `2017-01-10T02:50:26Z` which then caused issues for the discoverd cluster (we are investigating strategies for minimising the impact of this in #3766).

Without the logs from the third node, it's hard to determine the root cause here.

**Comment by lmars** [comment] 2017-01-12 01:04
I am going to close this, please open a new issue if you see this same behaviour again and try and get the logs.

**Closed by lmars** 2017-01-12 01:04 UTC
