### ISSUE TITLE
DeployerSuite.TestOneByOneStrategy timed out waiting for job events

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1223] opened 2015-03-11 21:09 UTC
```
FAIL: test_deployer.go:110: DeployerSuite.TestOneByOneStrategy

++ 21:02:35.002 created app pigs-doubt-lucan (dc03584bc3e44e908cbd875ebe399bcd)
++ 21:02:35.431 waiting for job events: map[printer:map[up:2]]
++ 21:02:35.564 got job event: printer 913f76f0-bea1b8356354487bab7c8f11d28e9bfc starting
++ 21:02:37.224 got job event: printer 33d36b3b-7eeac376fa1b4a74be18534f22f76730 starting
++ 21:02:38.734 got job event: printer 33d36b3b-7eeac376fa1b4a74be18534f22f76730 up
test_deployer.go:111:
    deployment := s.createDeployment(t, "printer", "one-by-one", "")
test_scheduler.go:74:
    t.Fatal("timed out waiting for job events: ", expected)
... Error: timed out waiting for job events: map[printer:map[up:2]]
```

https://ci.flynn.io/builds/20150311205929-abfc609f

**Comment by lmars** [comment] 2015-03-11 22:54
Duplicate of #907.

**Closed by lmars** 2015-03-11 22:54 UTC
Labels: bug, ci-flake
