### ISSUE TITLE
Force HTTPS-only on domain

### ISSUE THREAD

**Issue by obrienmd** [flynn/flynn#3269] opened 2016-08-11 14:52 UTC
Would love a feature (perhaps I'm missing something) for a domain to only be accessible via HTTPS. Ideally, HTTP requests would be redirected to HTTPS as well for such a domain.

**Comment by philiplb** [comment] 2016-08-11 15:07
Or maybe even deactivate port 80 for a route?

**Comment by titanous** [comment] 2016-08-11 15:09
@philiplb Do you mean return an error instead of a redirect when served over HTTP? What is the use case for that?

**Comment by philiplb** [comment] 2016-08-11 15:18
With the Amazon ELB, I can just not open port 80, no response there. Use case here: We want to open HTTP APIs only via HTTPs. The app developers would get an error if they even try to use unencrypted requests on port 80.

**Comment by titanous** [comment] 2016-08-11 15:24
Ah, I see, so Flynn would not listen on port 80 at all? That makes sense. Please file a separate issue.

**Comment by philiplb** [comment] 2016-08-11 15:26
Exact, will do. :)

**Comment by titanous** [comment] 2016-09-14 22:42
This is a duplicate of #2310.

**Closed by titanous** 2016-09-14 22:42 UTC
Labels: component/router, kind/enhancement
