### ISSUE TITLE
discoverd: timed out waiting for instances

### ISSUE THREAD

**Issue by chrisradford** [flynn/flynn#3640] opened 2016-11-08 00:48 UTC
I'm attempting to run `flynn-host fix --min-hosts=3` to restart the cluster after updating the `flynn-host` following the cluster no longer allowing deployments. I get the following logs when running the command:

```
INFO[11-08|00:32:39] found expected hosts                     n=3
INFO[11-08|00:32:39] ensuring discoverd is running on all hosts
INFO[11-08|00:32:39] checking flannel
INFO[11-08|00:32:39] flannel looks good
INFO[11-08|00:32:39] waiting for discoverd to be available
INFO[11-08|00:32:39] checking for running controller API
INFO[11-08|00:32:39] checking status of sirenia databases
INFO[11-08|00:32:39] checking for database state              db=postgres
INFO[11-08|00:32:39] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[11-08|00:32:39] found running leader                     fn=FixSirenia service=postgres
INFO[11-08|00:32:39] found running instances                  fn=FixSirenia service=postgres count=2
INFO[11-08|00:32:39] getting sirenia status                   fn=FixSirenia service=postgres
INFO[11-08|00:32:39] getting service metadata                 fn=FixSirenia service=postgres
INFO[11-08|00:32:39] getting primary job info                 fn=FixSirenia service=postgres job.id=flynn14777640901-3ce2f9c3-8bd8-45de-9719-cb169b05d32c
INFO[11-08|00:32:39] getting sync job info                    fn=FixSirenia service=postgres job.id=flynn14777640900-940856f1-8bf5-49fe-ab71-042fb79b84ba
INFO[11-08|00:32:39] terminating unassigned sirenia instances fn=FixSirenia service=postgres
INFO[11-08|00:32:39] checking for database state              db=mariadb
INFO[11-08|00:32:39] skipping recovery of db, no state in discoverd db=mariadb
INFO[11-08|00:32:39] checking for database state              db=mongodb
INFO[11-08|00:32:39] skipping recovery of db, no state in discoverd db=mongodb
INFO[11-08|00:32:39] checking for running controller API
INFO[11-08|00:32:39] killing any running schedulers to prevent interference
INFO[11-08|00:32:40] no controller web process running, getting release details from hosts
INFO[11-08|00:32:40] starting controller web job              job.id=flynn14777640900-4d4ffb0d-6165-42aa-ac55-e5d701ee536d release=86e72aa8-056b-4d90-80ba-57f3612bff1b
INFO[11-08|00:32:40] waiting for job to start
00:33:40.611032 host.go:157: discoverd: timed out waiting for instances
```

And the `flynn-host collect-debug-info` command runs but appears to hang (or takes 20+ minutes to run?), any suggestions as to how I can recover the cluster?

I should also add; I've tried looking through existing issues but can't see why `discoverd` would be timing out and why restarting each of the three hosts hasn't helped.

**Comment by titanous** [comment] 2016-11-08 15:35
Please tar up the logs from `/var/log/flynn` from each host and send them or a link to them to logs@flynn.io referencing this issue. Thanks!

**Comment by chrisradford** [comment] 2016-11-08 17:16
Uploading them now, thanks @titanous.

**Comment by IsNull** [comment] 2016-11-09 14:53
I get this error aswell when trying to do a clean install (on-prem, ubuntu vms). First I tried with 3 nodes, to debug also tried with only one node. It always times out at `INFO[11-09|15:40:35] Event: log: wait-hosts: start `

If I wait long enough it brings a timeout exception and then attempts to upload a secret gist, which then fails with strange "loop":

```
INFO[11-09|15:37:39] Event: log: t=2016-11-09T15:37:38+0100 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused" 
```

The flynn installation with `v20160918.1` worked on the same VMs/Hardware without any issue.

**Comment by josephglanville** [comment] 2016-11-09 15:02
@IsNull could you tar up `/var/log/flynn` on each of your cluster nodes and email them to `logs@flynn.io` with the issue number in the subject.

**Comment by IsNull** [comment] 2016-11-09 15:08
Apparently the gist was uploaded successfully anyway: https://gist.github.com/anonymous/e09fd96bde5ad3a821bb68ad0d82b9fe

**Comment by josephglanville** [comment] 2016-11-09 15:28
Your issue is entirely seperate to the one this ticket is about, yours is a failed bootstrap caused by discoverd crashing after receiving subnet/resolver data from flannel. I'm looking into the root cause now but it could be our code isn't handling something in your network configuration.
Could you open a new issue regarding the failed bootstrap and send through a tarball of `/var/log/flynn` for every node.

**Comment by IsNull** [comment] 2016-11-09 15:52
@josephglanville Thanks for your fast response - sorry did not see that it is an unrelated issue. I have opened a new one and also uploaded the node logs in issue #3653

**Comment by chrisradford** [comment] 2016-11-10 11:11
Any idea if it's possible to bring up a single container / host so I can grab a copy of the Postgres databases?

**Comment by lmars** [comment] 2016-11-10 19:55
@chrisradford I have looked through the logs and it looks like network issues between the nodes causes discoverd to mark a lot of services as down, which is especially problematic for the PostgreSQL cluster and results in quite a lot of churn.

That churn eventually lead to PostgreSQL being unable to start due to a lack of available memory:

```
t=2016-11-05T10:57:06+0000 lvl=eror msg="error pulling basebackup" app=postgres component=postgres fn=assumeStandby upstream=100.100.46.83:5432 err="fork/exec /usr/lib/postgresql/9.5/bin/pg_basebackup: cannot allocate memory"
```

and then (I assume after a reboot or two) because of a lack of available disk space:

```
t=2016-11-05T12:16:43+0000 lvl=info msg="pulling basebackup" app=postgres component=postgres fn=assumeStandby upstream=100.100.5.64:5432
pg_basebackup: could not write to file "/data/db/base/16824/2613": No space left on device
t=2016-11-05T12:17:17+0000 lvl=eror msg="error pulling basebackup" app=postgres component=postgres fn=assumeStandby upstream=100.100.5.64:5432 err="exit status 1"
```

Your data still exists on disk, but given PostgreSQL isn't starting, I can't give you an easy command to fetch the data.

The best thing to do would be for you to ping us in IRC (#flynn on Freenode) and we can help you get a backup.

---

Here are some excerpts from the logs (mainly for our understanding so we can fix any issues):

The cluster was booted around `2016-10-29T18:10:50Z`, and here is discoverd job `flynn14777640900-502f464e-cb06-4dbf-ba0c-9a59126d8628` having issues contacting `x.x.x.251` around `2016-10-29T21:52:38Z`:

```
2016/10/29 21:52:29 tcp.Mux: read header byte: read tcp4 x.x.x.193:1111->x.x.x.251:40928: i/o timeout
2016/10/29 21:52:38 [WARN] raft: Failed to contact x.x.x.251:1111 in 500.220479ms
2016/10/29 21:53:10 [WARN] raft: Failed to contact x.x.x.251:1111 in 500.318509ms
...
2016/10/29 21:53:49 [DEBUG] raft: Failed to contact x.x.x.251:1111 in 5.74603309s
2016/10/29 21:53:49 [DEBUG] raft: Failed to contact x.x.x.251:1111 in 6.222256186s
...
2016/10/29 21:54:10 [DEBUG] raft: Failed to contact x.x.x.251:1111 in 17.043081249s
2016/10/29 21:54:11 [DEBUG] raft: Failed to contact x.x.x.251:1111 in 17.507477815s
...
2016/10/29 21:54:12 tcp.Mux: read header byte: read tcp4 x.x.x.193:1111->x.x.x.251:41350: i/o timeout
```

During this time, services are marked as expired, for example `postgres`:

```
t=2016-10-29T21:53:44+0000 lvl=info msg="marking instance for expiry" component=discoverd fn=EnforceExpiry service=postgres instance.id=f126cc780e87380a98f198cc06eca5c6 instance.addr=100.100.5.2:543
t=2016-10-29T21:54:09+0000 lvl=info msg="marking instance for expiry" component=discoverd fn=EnforceExpiry service=postgres instance.id=71fe3a8d0e68d2838ec20cce1f8456e8 instance.addr=100.100.90.2:5432
t=2016-10-29T21:54:10+0000 lvl=info msg="marking instance for expiry" component=discoverd fn=EnforceExpiry service=postgres instance.id=10d812998d674be1dd8c2a152301c338 instance.addr=100.100.46.2:5432
```

Communication with `x.x.x.251` is eventually re-established at `2016-10-29T21:54:22Z`:

```
2016/10/29 21:54:22 [DEBUG] raft: Failed to contact x.x.x.251:1111 in 28.378407984s
2016/10/29 21:54:22 [DEBUG] raft-net: x.x.x.193:1111 accepted connection from: x.x.x.251:41468
2016/10/29 21:54:22 [WARN] raft: Rejecting vote request from x.x.x.251:1111 since we have a leader: x.x.x.193:1111
```

Shortly after this happens, some services which were marked for expiry come back up, for example the postgres services:

```
t=2016-10-29T21:54:26+0000 lvl=info msg="broadcasting up event" component=discoverd fn=broadcast event=up service=postgres instance.id=10d812998d674be1dd8c2a152301c338 instance.addr=100.100.46.2:5432
t=2016-10-29T21:54:30+0000 lvl=info msg="broadcasting up event" component=discoverd fn=broadcast event=up service=postgres instance.id=71fe3a8d0e68d2838ec20cce1f8456e8 instance.addr=100.100.90.2:5432
```

This flapping of the postgres services leads to state machine churn, and occasionally PostgreSQL exiting with `panic: unexpected role deposed`.

It is unclear whether the network issues between the nodes is the cause of services being marked as down, or is just another effect caused by some other underlying issue (e.g. very high load / no available memory etc.). Logging critical resource usage (#3484) would be invaluable here.

**Closed** 2017-05-18 09:12 UTC
