### ISSUE TITLE
Failing to install Flynn (expired manifest)

### ISSUE THREAD

**Issue by sdimitrov** [flynn/flynn#3911] opened 2017-02-10 16:41 UTC
err="tuf: failed to decode root.json: expired at 2017-02-10 16:07:43 +0000 UTC"

Same as #2436

**Comment by lmars** [comment] 2017-02-10 16:43
@sdimitrov thanks for reporting, I am pushing a fix for this.

**Comment by lmars** [comment] 2017-02-10 17:34
The updated manifest is being rolled out, it can take around 10 minutes for cache invalidation, I'll close this issue once it is fully rolled out.

---

For future reference, to bump the root manifest expiry:

* add then revoke a key:

```
$ cd /etc/flynn/tuf

$ tuf gen-key targets
Enter root keys passphrase:
Generated targets key with ID 5d941c09ce2579fbd05475049d0bf4d3d6d85724efa6f27c2b0b14bf0824aac4

$ tuf revoke-key targets 5d941c09ce2579fbd05475049d0bf4d3d6d85724efa6f27c2b0b14bf0824aac4
Enter root keys passphrase:
```

* verify the change is what was intended by checking the diff between the staged and committed root.json:

```diff
$ diff -Naur <(jq . repository/root.json) <(jq . staged/root.json)
--- /dev/fd/63  2017-02-10 16:58:43.875633364 +0000
+++ /dev/fd/62  2017-02-10 16:58:43.871633604 +0000
@@ -2,7 +2,7 @@
   "signed": {
     "_type": "Root",
     "consistent_snapshot": true,
-    "expires": "2017-02-10T16:07:43Z",
+    "expires": "2018-02-10T16:57:09Z",
     "keys": {
       "1741ffffe790cbcce09d23b2c69637bebf16144dfa99b8c0b777ee429199b076": {
         "keytype": "ed25519",
@@ -55,13 +55,13 @@
         "threshold": 1
       }
     },
-    "version": 8
+    "version": 10
   },
   "signatures": [
     {
       "keyid": "85bbb9f26684e5ab9adfa224eb8b79d69a094b5c514de5ccebe9f46fb81a0070",
       "method": "ed25519",
-      "sig": "8d597b4e2bc5a4c8a4c5ccd3ea5d3eb95fff3e9fdc9140b0c6986fc57379d8b2bd9c464bced8e357e714bd8b80864b673d8acd818942bcdd1b0c7cdbc34bb10e"
+      "sig": "8032dffa23051ec22696796259dffecccc14bfeacea0ee39a99475fdb8ae91f46f20c2bedd0a2995380013f1822f312f661f2263f066ad49bc95213356515903"
     }
   ]
 }
```

* generate a new snapshot / timestamp & commit:

```
$ tuf snapshot
$ tuf timestamp
$ tuf commit
```

* roll out the change:

```
$ cd ~/go/src/github.com/flynn/flynn
$ source script/lib/ui.sh
$ source script/lib/aws.sh
$ sync_cloudfront "/etc/flynn/tuf/repository/" "s3://flynn/tuf/"
```

We should probably add a `tuf` command to just bump the expire time.

**Comment by lmars** [comment] 2017-02-10 17:43
@sdimitrov the cache invalidation is now complete, please try installing Flynn again.

**Closed by lmars** 2017-02-10 17:43 UTC

**Comment by sdimitrov** [comment] 2017-02-10 19:10
Just tried it again on a clean DO droplet, still getting the same error. I'll try again later.
