### ISSUE TITLE
App is frozen to specific release

### ISSUE THREAD

**Issue by nlsrchtr** [flynn/flynn#3407] opened 2016-09-20 13:02 UTC
Thanks for your work on this! It is a nice environment to work and deploy apps.

But currently I'm facing a strange situation. I have an app running and can push new code successful and it also spins up a new release, but the routing is still going to an old release:

```
% flynn ps
ID                                            TYPE    STATE    CREATED         RELEASE
364fa8cc-acdb-4b22-b352-2bdae24963a9          worker  pending  6 days ago      4f033f64-30dd-4afc-94a0-8922c201cf08
27e5c863-47c0-4710-9804-83375331af7f          worker  pending  6 days ago      63c3c3de-d89c-467b-b687-d8e7f4fae259
flynn02-89381478-4530-43bd-9f3b-343963ecca2f  web     up       6 days ago      4f033f64-30dd-4afc-94a0-8922c201cf08
flynn01-482d8da1-8e76-4af4-8b2c-46e455db50cd  web     up       6 days ago      4f033f64-30dd-4afc-94a0-8922c201cf08
flynn01-0e2c46e8-8cce-4722-9542-0b0ab7781f9f  worker  up       6 days ago      4f033f64-30dd-4afc-94a0-8922c201cf08
flynn01-d2ec7782-1e79-4181-9c2a-79b08aafa471  clock   up       40 minutes ago  d8c597c9-49b1-4c5e-8c3f-eaabd128ebff
flynn01-246b7637-94a9-4937-818c-b82b20b3f9aa  web     up       40 minutes ago  d8c597c9-49b1-4c5e-8c3f-eaabd128ebff
flynn01-c9cf8936-d094-4cab-b9b2-5e7701bce440  worker  up       40 minutes ago  d8c597c9-49b1-4c5e-8c3f-eaabd128ebff
flynn01-676eab83-e1d6-4c0b-ad2c-7235b9e15b04  clock   up       37 minutes ago  4f033f64-30dd-4afc-94a0-8922c201cf08
```

Release `4f033f64-30dd-4afc-94a0-8922c201cf08` is never shutdown, even after rebooting the whole cluster and several redeployments of the app - with successful results. As you can see release `d8c597c9-49b1-4c5e-8c3f-eaabd128ebff` was created after `4f033f64-30dd-4afc-94a0-8922c201cf08` but doesn't get any traffic.

We're running version `v20160512.0`. Since I have trouble updating the setup, I would hope there is a way to fix this situation somehow and get the latest release of the apps up and running.

**Comment by lmars** [comment] 2016-09-20 13:11
@nlsrchtr can you run `sudo flynn-host collect-debug-info` on a host in your cluster and post the resulting gist?

The issue here seems to be an old release is still scaled up (which can happen if deploys fail in certain ways, I pushed a fix for that recently). Check `flynn scale --all` and you can scale down the old release with `flynn scale -r RELEASE_ID worker=0 web=0`, but please collect the debug info first to help us understand exactly how this happened.

**Comment by nlsrchtr** [comment] 2016-09-20 13:28
Since I tried updating one cluster node with `--clean` #3408 I think the logs aren't any helpful. Maybe I can send you the logs after fixing the current situation.

Thanks for the hint with scaling down. I was wondering if the system could try to self-heal in such situations. Maybe a check how long a container is `pending` and after a configurable timeout it will get killed and a new release would be tried. Just a quick thought...

**Comment by lmars** [comment] 2016-09-20 13:36
> I was wondering if the system could try to self-heal in such situations. Maybe a check how long a container is pending and after a configurable timeout it will get killed and a new release would be tried. Just a quick thought...

The old release remained scaled up due to a bug which is now fixed, but Flynn has no way to really know what scale your app should be at (e.g. you could have manually ran `flynn -r RELEASE scale web=1` in which case that web process will continue to run regardless of whether you deploy or not).

Containers in the `pending` state are waiting to be scheduled and are usually the replacement of a job which recently crashed.

Flynn will never create a release on your behalf, new releases are always created by users and scaled, and then it is Flynn's job to make sure those releases continue to run at the requested scale. Ultimately you hit a bug here where a failed deployment left an old release scaled up, and we have fixed that in more recent versions.

**Comment by lmars** [comment] 2016-09-20 13:38
Oh in fact those jobs stuck in the `pending` state are due to the fact that you restarted the cluster and the scheduler has not realised they are no longer pending, another bug which is also fixed in the latest version.

**Closed** 2016-09-21 07:45 UTC

**Comment by nlsrchtr** [comment] 2016-09-21 08:47
After updating and restoring from the backup, the situation was the same. So I collected the debug information for you. With scaling down the release old release, we are now on the new release.

How can I contact you to send you the link for the debug information in private? It contains some information I'm not willing to share here.

**Comment by philiplb** [comment] 2016-09-21 08:49
logs@flynn.io

**Comment by josephglanville** [comment] 2016-09-21 08:52
Yep, logs@flynn.io will goes to the Flynn development team. If you could please include the issue number in the subject that would be great, thanks!

**Comment by titanous** [comment] 2016-09-21 14:02
@nlsrchtr If the backup was taken before the old release was scaled down, then it makes sense for the release to be scaled up after restore. The root cause of the issue has been fixed, so this is just a vestige of the issue from the previous cluster that was fixed as soon as you scaled it down on the new cluster. Is there any other reason for us to look at the logs you sent?

**Comment by nlsrchtr** [comment] 2016-09-21 15:57
@titanous No, I don't think there is. Thanks!
