### ISSUE TITLE
flynn routes does not work

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#3784] opened 2016-12-24 18:44 UTC
we have an app called `shop-app` with more than 1000 routes. I recently noticed last 6 routes does not work. it simply gives Service Unavailable. there is no error logged and I believe it does not route to this node app at all

[debug logs](https://dl.dropboxusercontent.com/u/3116541/flynn-host-debug.tar.gz)

**Comment by hadifarnoud** [comment] 2016-12-27 20:24
any idea why these routes do not work?

**Comment by lmars** [comment] 2016-12-27 23:24
@hadifarnoud do the routes show in `flynn route` for the app?

**Comment by hadifarnoud** [comment] 2016-12-28 07:05
yes, I can see the route in `flynn route`

**Comment by mrrooijen** [comment] 2017-01-17 02:58
I've been sandboxing Flynn for a bit and just decided to deploy a Docker image rather than using the git push workflow just to try it out. What ended up happening is that rather than creating a `web` service, it creates an `app` service. I decided to create a route to that `app` service with the following command:

    flynn route add http -s myapp-app www.example.com

Then I added a CNAME record to point `www.example.com` to the `myapp.CLUSTERNAME`, and I too got the `Service Unavailable` error message. I then removed the newly added route:

    flynn route remove <route-id>

I then proceeded to add a new route again without the `-s` option:

    flynn route add http www.example.com

It then added a route for the `myapp-web` service (the default, which doesn't exist) but now the route works and actually proxies the requests to `myapp-app` when accessing the route via `www.example.com`.

Bug?

**Comment by titanous** [comment] 2017-01-17 17:20
@mrrooijen This is intentional, currently the service name is manually specified internally, not constructed from the app/process type, so for the Docker compatibility we're just hacking it to be `APPNAME-web`. This will change in the future, sorry for the confusion.

**Comment by mrrooijen** [comment] 2017-01-17 19:08
@titanous  No problem! Btw, what if I want to deploy two different services using a Docker image, each with a different `flynn route`, is that currently possible? If not, is it possible to have multiple routes when using `Procfile` entries?

**Comment by lmars** [comment] 2017-01-18 13:59
@mrrooijen anything more custom than the default of having a single `MYAPP-web` service currently requires updating the release manually with `flynn release update release.json`.

See [this gist](https://gist.github.com/lmars/404531abc014a75250dbc5558d751b11) for instructions on adding a second process type (which in that specific case was a TCP service `MYAPP-mqtt` which could be routed to).

This will change in the near future when we add support for a Flynnfile which will support custom configurations (#1084).

**Comment by mrrooijen** [comment] 2017-01-18 14:53
@lmars 👍

**Comment by hadifarnoud** [comment] 2017-01-25 10:35
did you find why it happens @lmars ?

**Comment by titanous** [comment] 2017-02-28 14:47
This looks like a dupe of #3943, closing.

**Closed by titanous** 2017-02-28 14:47 UTC
