### ISSUE TITLE
git push flynn fails after changing fallback(global) certificate

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2034] opened 2015-10-27 21:30 UTC
```
flynn -a router env set TLSCERT="$TLSCERT" TLSKEY="$TLSKEY"
git push flynn
fatal: unable to access 'https://git.xxx.com/kudus-pacify-archipelago.git/': Server aborted the SSL handshake
```

I removed the related self-signed certs from my git config, didn't help.

**Comment by titanous** [comment] 2015-10-27 22:24
I'm unable to replicate this issue locally. It sounds like there is no route set up for the URL you are trying to use in the git remote.

**Comment by titanous** [comment] 2015-10-27 22:33
Looks like this was user error, confirmed on IRC. Closing.

**Closed by titanous** 2015-10-27 22:33 UTC
