### ISSUE TITLE
flynn-install --clean doesn't correctly handle filesystems that are still mounted

### ISSUE THREAD

**Issue by simonamor** [flynn/flynn#3941] opened 2017-02-25 13:55 UTC
After a failed bootstrap (due to the firewall) I had a flynn installation that was stuck with only some of the apps actually installed. Repeating the bootstrap command fails because of conflicting ports in use etc. After downloading flynn-install, I tried --clean and it failed to unmount /flynn-default as there were 3 other directories mounted inside it

```
flynn-default                    49233152       0  49233152   0% /flynn-default
flynn-default/data               49233152       0  49233152   0% /flynn-default/data
flynn-default/squashfs           49233152       0  49233152   0% /flynn-default/squashfs
flynn-default/ext2               49233152       0  49233152   0% /flynn-default/ext2
```

```
root@flynn:~# bash /tmp/install-flynn --clean --zpool-create-device /dev/sdb --zpool-create-options "-f"
===> 13:31:39.876 *** WARNING ***
===> 13:31:39.878 About to stop Flynn and remove all existing data
===> 13:31:39.882 Are you sure this is what you want?
(yes/no): yes
===> 13:31:41.383 stopping flynn-host daemon
===> 13:31:41.520 killing old containers
No .containerinit found running; none killed.
===> 13:31:41.549 destroying ZFS volumes
===> 13:31:41.555 running "sudo umount /flynn-default"
umount: /flynn-default: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
===> 13:31:41.568 ERROR: failed to run "sudo umount /flynn-default", exit status 32
root@flynn:~#
```

After manually unmounting /flynn-default/*, the flynn-install command worked as expected.
```
root@flynn:~# umount /flynn-default/*
root@flynn:~# umount /flynn-default
```

**Comment by bbaptist** [comment] 2017-03-08 15:49
Might be a dupe of #3773

**Comment by titanous** [comment] 2021-02-18 21:55
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

**Closed by titanous** 2021-02-18 21:55 UTC
