### ISSUE TITLE
Flynn Dashboard Cluster Status Null 

### ISSUE THREAD

**Issue by mbreisch** [flynn/flynn#3063] opened 2016-07-06 17:46 UTC
My dashboard cluster status is not rendering and showing null do to an apparent 500 status code error.

How should I go about resolving this?

![flynn_dashboard_status](https://cloud.githubusercontent.com/assets/8809492/16628513/09820b9a-4380-11e6-81dd-92eb800b5c6f.png)

**Comment by titanous** [comment] 2016-07-06 17:49
@jvatic The status endpoint returns 500 when unhealthy, does the UI not handle that?

@mbreisch Can you curl status.CLUSTER_DOMAIN? If you're outside of the local network you may need to add a `?key=SECRET` URL param that can be retrieved with `flynn -a status env get AUTH_KEY`

**Comment by mbreisch** [comment] 2016-07-06 18:00
@titanous I seem to get a no matches found error, when running curl with the key.

**Comment by titanous** [comment] 2016-07-06 18:00
Make sure you escape the question mark in the shell or put the whole URL in quotes.

**Comment by mbreisch** [comment] 2016-07-06 18:03
Okay, so the json output is:
```
{
  "data": {
    "status": "unhealthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller-worker": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "dashboard": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "docker-receive": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "flannel": {
        "status": "unhealthy",
        "version": "v20160624.1"
      },
      "gitreceive": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "mariadb": {
        "status": "unhealthy"
      },
      "postgres": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "router": {
        "status": "healthy",
        "version": "v20160624.1"
      }
    },
    "version": "v20160624.1"
  }
}
```

**Comment by titanous** [comment] 2016-07-06 18:06
Two things are going on:

1. There's a bug in the dashboard (@jvatic will fix)
2. The flannel service is showing as unhealthy. How many nodes in the cluster? I can walk you through tracking down why this is the case.

**Comment by mbreisch** [comment] 2016-07-06 18:07
Thanks. I have a three node cluster.

**Comment by titanous** [comment] 2016-07-06 18:12
Okay, retrieve the IP addresses of the `flannel.1` interface on each host with `ip addr show flannel.1`. Once you have that, try checking the other two hosts from each host by running `curl -v OTHER_FLANNEL_IP:5002/ping` and checking for a 200 OK. If everything is working, you should end up getting six successful responses.

**Comment by mbreisch** [comment] 2016-07-06 18:29
I have tried curling on every host and I get a time out and connection refused error. Could my ufw firewall be blocking the curl?

**Comment by titanous** [comment] 2016-07-06 18:30
Yes, the ufw firewall is very likely the cause. Take a look at this blog post for details on configuring it properly: https://philiplb.de/flynn/2016/04/19/flynn-ufw/

**Comment by mbreisch** [comment] 2016-07-06 18:36
I actually used that post as a guide for setting up the firewall. My settings are exactly the same when I run `sudo ufw status verbose`:
$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), allow (routed)
New profiles: skip

```
To                         Action      From
--                         ------      ----
22                         ALLOW IN    Anywhere
80                         ALLOW IN    Anywhere
443                        ALLOW IN    Anywhere
3000:3500/tcp              ALLOW IN    Anywhere
Anywhere                   ALLOW IN    <flynn_IP1>
Anywhere                   ALLOW IN    <flynn_IP2>
Anywhere                   ALLOW IN    <flynn_IP3>
Anywhere on flynnbr0       ALLOW IN    Anywhere
22 (v6)                    ALLOW IN    Anywhere (v6)
80 (v6)                    ALLOW IN    Anywhere (v6)
443 (v6)                   ALLOW IN    Anywhere (v6)
3000:3500/tcp (v6)         ALLOW IN    Anywhere (v6)
Anywhere (v6) on flynnbr0  ALLOW IN    Anywhere (v6)
```
Should I try to make a rule for the flannel interface?

**Comment by titanous** [comment] 2016-07-06 18:37
Yeah, try adding a rule allowing all traffic to/from `flannel.0`

**Comment by mbreisch** [comment] 2016-07-06 18:40
Sorry flannel.0 or flannel.1. I only see flannel.1 in my ifconfig?

**Comment by titanous** [comment] 2016-07-06 18:40
flannel.1, my bad.

**Comment by mbreisch** [comment] 2016-07-06 18:58
That did it. I ran `sudo ufw allow in on flannel.1` reloaded the firewall and now pinging works between hosts over flannel. Just checked the output of the curl to the status app:
```
{
  "data": {
    "status": "healthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "controller-worker": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "dashboard": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "docker-receive": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "flannel": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "gitreceive": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "mariadb": {
        "status": "unhealthy"
      },
      "postgres": {
        "status": "healthy",
        "version": "v20160624.1"
      },
      "router": {
        "status": "healthy",
        "version": "v20160624.1"
      }
    },
    "version": "v20160624.1"
  }
}
```

Status page now works too:
![flynn_status_page_fixed](https://cloud.githubusercontent.com/assets/8809492/16630706/8f9c32b0-4389-11e6-8e13-5c195957ac83.png)

Thanks for all your help. One final question why is my mariadb considered unhealthy? Is it because it is not in use by any apps?

Also, a thought, maybe more documentation on the firewall should be added. When I have a little time I can make a pull request for the docs about setting up installation regarding ufw configuration. This way the process is formalized.

**Comment by titanous** [comment] 2016-07-06 18:59
Yes, mariadb is optional, and only enabled when an app uses it. We need to clean up the status service to just not show it in this case instead of marking it as unhealthy.

**Comment by mbreisch** [comment] 2016-07-06 19:01
Okay, good--just wanted to make sure everything that was necessary is operational.

I'll try to make a pull request on the docs within the next few days detailing the ufw configurations that worked for me.

Thanks again for all of your help.

**Comment by philiplb** [comment] 2016-07-06 19:51
I updated the posting. I wonder why it worked for me so far... :)

**Closed** 2016-07-06 20:07 UTC
Labels: bug, dashboard
