### ISSUE TITLE
MariaDB hangs, process list shows "waiting for semi-sync ack from slave"

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#3197] opened 2016-07-28 06:23 UTC
The process never seems to complete. Manually killing it via `kill <pid>` allows the requested operation to complete. The next operation triggers the same issue again, though.

**Comment by josephglanville** [comment] 2016-07-28 06:25
Could you describe how you got to this point?

Is this on first creating a resource with `flynn resource add mysql` or at some point after this?

**Comment by josephglanville** [comment] 2016-07-28 06:27
Also if you could run `flynn-host collect-debug-info` and post the gist link here or use the `--tarball` option and email it to logs@flynn.io that would be really helpful in diagnosing what went wrong.

**Comment by michaelyork** [comment] 2016-07-28 06:27
Created database via UI as standalone, opted to create external route, then linked to existing app.

Partially imported a SQL dump from dokku via Sequel Pro and the external route, then noticed the import had hung.

**Comment by michaelyork** [comment] 2016-07-28 06:29
Happy to – actually on a different machine than the one I provisioned Flynn with and forgot to pull over the .flynnrc contents. Is there a way for me to add the cluster to this machine's CLI without the original .flynnrc, assuming I can log in to the dashboard?

**Comment by josephglanville** [comment] 2016-07-28 06:46
The easiest way is to copy `.flynnrc`, otherwise you will need to get the certificate pin. Which can be done and I can walk you through that if required. However in this case you don't need to use the `flynn-cli` but rather `flynn-host` which needs to be run on a cluster node. If you used the installer to setup your cluster you can access the nodes by following the documentation here https://flynn.io/docs/installation/cloud#ssh-access

**Comment by michaelyork** [comment] 2016-07-28 07:04
Gotcha. I set them up manually so let me just circle back around here tomorrow when I have access to CLI. FWIW, I'm able to consistently reproduce the hang.

**Comment by josephglanville** [comment] 2016-07-28 10:07
I have reproduced this restoring largish dumps. Working on finding the root cause now.

**Comment by josephglanville** [comment] 2016-07-28 13:18
@michaelyork For now you can work around the issue by running `SET GLOBAL rpl_semi_sync_master_timeout = 1000`on the MariaDB master. The easiest way to do that is to use `flynn -a mariadb mysql console`. I am working on an actual fix that won't require lowering the semis-sync timeout.

**Comment by michaelyork** [comment] 2016-07-29 00:15
@josephglanville Will that cause any issues with replication / data integrity with some things not making it over to the slave? If so, happy to wait for the real fix.

**Comment by josephglanville** [comment] 2016-07-29 08:21
@michaelyork the workaround could feasibly lose data in very specific scenarios but it is unlikely as when the timeout is reached it will attempt to renegotiate semi-sync replication again. It also has only a small window where it will hang (when the master begins writing to a new binlog file).

I am working with the upstream developers now to narrow down the exact cause so the real fix may take a while to arrive.

**Comment by josephglanville** [comment] 2016-08-13 03:45
An update on this:
I have reproduced outside of Flynn and have opened an upstream bug here: https://jira.mariadb.org/browse/MDEV-1055

**Comment by josephglanville** [comment] 2016-08-16 10:48
Located the root cause today and fix was tested and merge upstream. It will be in the next MariaDB 10.1 release.

**Comment by titanous** [comment] 2016-08-16 13:30
For reference this was fixed in https://github.com/MariaDB/server/commit/48fbb2bf07515425edaf511ac2e17a575ae37713

**Comment by josephglanville** [comment] 2016-09-01 05:44
The upstream fix has been released in [MariaDB 10.1.17](https://mariadb.com/kb/en/mariadb/mariadb-10117-changelog/) and will be incorporated into nightly builds from now on and will ship in the next stable release.

**Comment by josephglanville** [comment] 2016-09-03 16:31
This has gone out in a nightly, will close this now as it will be part of the next stable release.

**Closed by josephglanville** 2016-09-03 16:31 UTC
Labels: component/mariadb, kind/bug, upstream/mariadb
