### ISSUE TITLE
Too many colons in address for flynn-webhook-deploy

### ISSUE THREAD

**Issue by cromulus** [flynn/flynn#3288] opened 2016-08-14 01:05 UTC
In a new cluster, launching an instance of flynn-webhook-deploy crashes with this error:

`[2016-08-12T14:06:55.346829542Z] 14:06:55.346690 postgres.go:54: Get http://192.168.200.11:1111,192.168.200.12:1111,192.168.200.13:1111/services/postgres: dial tcp: too many colons in address 192.168.200.11:1111,192.168.200.12:1111,192.168.200.13:1111`

Debug Log here: https://gist.github.com/b6a7a3421766bc5c97b8c7749538757b

[Prior issue](https://github.com/lmars/flynn-webhook-deploy/issues/6) logged at flynn-webhook-deploy was redirected here.

**Comment by titanous** [comment] 2016-08-14 01:06
@lmars Are you sure the problem isn't outdated godeps in flynn-webhook-deploy?

**Comment by lmars** [comment] 2016-08-14 23:17
@titanous this was indeed an issue with outdated dependencies.

@cromulus I have pushed a fix to master of flynn-webhook-deploy, let me know if you have any more issues.

**Closed by lmars** 2016-08-14 23:17 UTC
