### ISSUE TITLE
Cannot modify App's ENV Variables in the dashboard

### ISSUE THREAD

**Issue by aaronfranco** [flynn/flynn#2822] opened 2016-05-13 00:09 UTC
I imported an app form a file using the "--name" command. I then try to modify its ENV variables. I get this in the console:

undefined:1 Uncaught (in promise) undefined
undefined:1 Uncaught (in promise) Timed out waiting for deployment completion
undefined:1 Uncaught (in promise) undefined

No network errors.

**Comment by titanous** [comment] 2016-05-13 00:10
Is there anything in the app log? That error should be surfaced in the UI, but the underlying cause is the deploy error.

**Comment by aaronfranco** [comment] 2016-05-13 00:46
There are no errors in the app log, and there are no deploy logs for the app.

**Comment by aaronfranco** [comment] 2016-05-13 20:40
Now I get the followign error:

https://controller.[custom-url]/events?key=af8d85423... Failed to load resource: net::ERR_TIMED_OUT

**Comment by aaronfranco** [comment] 2016-05-13 20:41
It successfully deploys the changes, but fails in the UI of the dashboard.

**Comment by okolehao** [comment] 2016-06-02 17:32
I'm trying to create new variables and save them in the dasboard UI and it just hangs

![image](https://cloud.githubusercontent.com/assets/3718695/15754525/844f5370-28c6-11e6-8d75-910b93f18dc5.png)

**Comment by titanous** [comment] 2016-06-02 19:37
@okolehao Any errors in the console? Have you tried using the `flynn` CLI to do the same?

**Comment by jvatic** [comment] 2017-01-03 22:24
Closing as I'm unable to reproduce with the latest version of Flynn.

**Closed by jvatic** 2017-01-03 22:24 UTC
Labels: component/dashboard, kind/bug
