### ISSUE TITLE
Flynn analog for Digital Ocean Monitoring?

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#4027] opened 2017-04-04 23:58 UTC
I know it was just [released today ](https://www.digitalocean.com/company/blog/introducing-monitoring/) but are there plans for future updates for Flynn to match these monitoring features.

The CPU, Disk Usage and Memory ones would be nice to have.
(I'm unsure if blobstorage would be capable of handling this data)

Metrics
- CPU
- Disk I/O
- Memory
- Disk usage
- Inbound and outbound bandwidth
- A process list ordered by CPU or memory usage

Alerts
- Slack Alerts — Post to your team's Slack channel when a new alert is triggered.
- Email Notifications — Send emails when a new alert alert is triggered.

**Comment by titanous** [comment] 2017-04-28 19:15
Dupe of #201.

**Closed by titanous** 2017-04-28 19:15 UTC
