### ISSUE TITLE
crashing process does not allow scale down

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#4289] opened 2017-11-25 12:37 UTC
I have an app that rapidly crashes `web` process and it tries to respawn. it creates a very long list of logs which makes flynn dashboard unresponsive. I can't scale it down to stop the respawning either. I even went to older release without the issue but still web process is crashing.

I need to clean up the log and scale down the app to stop creating massive error logs.

**Comment by titanous** [comment] 2017-11-25 19:22
This sounds like a duplicate of #3083. H ave you tried scaling it down with `flynn scale`?

**Comment by hadifarnoud** [comment] 2017-11-25 19:24
I managed to fix the issue with doing scale on a release. that issue is fixed.

logs are so many that crashes the dashboard. I wonder if there is a way to get rid of them?

**Comment by lmars** [comment] 2017-11-27 11:43
Glad you fixed the scale, the dashboard logs issue has been reported in #4238.

**Closed by lmars** 2017-11-27 11:43 UTC
