### ISSUE TITLE
App failing and constantly restarting chewing huge disk space

### ISSUE THREAD

**Issue by benkaiser** [flynn/flynn#3396] opened 2016-09-16 10:09 UTC
Flynn log: https://gist.github.com/anonymous/5f787ebc53c3964a217c219045a836ae

I set up a fresh install, deployed one application, all fine. Then I deployed a second application, a ghost blog (similar to the one at https://github.com/flynn-examples/ghost-on-flynn ) but it was failing on deploy. I tried to address the issue and deployed again, except the second time it did not spin up the web worker. So I went to the dashboard and scaled it up to one worker. It ran the web job and crashed, then it kept attempting to restart again and again. This was fine, I needed to fix the issue, but what I couldn't believe is that as I ran a `du -h` whilst it kept doing it, I could see my disk usage grow by ~1GB per minute!

This is what caused me to nuke my setup and do a fresh install, the disk usage. I'm running on a 24GB server and it just annihilates my disk space. I'm assuming by the looks of some of the logs it is creating a new image every single time it tries to spin up the job, and when I did a `du -h -d 1` on one of those failed images, it's 342MB!

Is there a reason these aren't cleaned up after being used? like especially the failed ones? I can imagine rolling back to a successful build, but keeping around a 300MB image every time a failed build occurs seems ludicrous.

In the short term, is there any way to clean up the images of just the failed builds?

**Comment by benkaiser** [comment] 2016-09-16 10:11
Could be a dupe of https://github.com/flynn/flynn/issues/3314

But I also tried the garbage collection script  there and it did not alter the disk usage

**Comment by benkaiser** [comment] 2016-09-16 10:16
The script linked here: https://github.com/flynn/flynn/issues/3163#issuecomment-234273239

Seemed to do a decent job of cleaning up, reducing my disk space back to 8.3GB (which is where it was before all the failed builds).

Is this fixed in master? because on the latest released install script I have installed it doesn't seem fixed.

**Comment by benkaiser** [comment] 2016-09-16 10:26
Upon deleting that said blog application I saw:

```
$ flynn delete
Are you sure you want to delete the app "blog"? (yes/no): yes
Deleted blog (removed 1 routes, deleted 2 releases, deprovisioned 1 resources)
```

With the disk usage un-altered (9.1G).

Then ran the `flynn-cleanup.sh` script mentioned in my previous comment with no changes in disk-space. So when application are deleted, their images and resources don't seem to be cleaned up on disk.

**Comment by lmars** [comment] 2016-09-16 15:03
@benkaiser the issue here is that Flynn is not waiting for the container to fully exit before cleaning up the temporary AUFS layer, so removing it leads to `EBUSY` as it is still mounted in the container's namespace:

```
t=2016-09-14T23:00:32+0000 lvl=eror msg="error running pinkerton cleanup" app=host pid=32399 host.id=ubuntu component=backend backend=libcontainer fn=cleanup job.id=ubuntu-e1631164-245a-41c5-aec3-43db2d8956ab err="rename /var/lib/docker/aufs/mnt/tmp-ubuntu-e1631164-245a-41c5-aec3-43db2d8956ab /var/lib/docker/aufs/mnt/tmp-ubuntu-e1631164-245a-41c5-aec3-43db2d8956ab-removing: device or resource busy"
```

I am working on a patch to fix that, but in the meantime running the leaked AUFS cleanup script you linked to should remove these.

An explanation of the behaviour you have observed:

> as I ran a du -h whilst it kept doing it, I could see my disk usage grow by ~1GB per minute!

When a job is run for your app, the slug tarball (built during `git push`) is downloaded into the job's temporary image layer and extracted into `/app`, so if your slug is say 100MB and 200MB uncompressed, this means 300MB is used for every job. This usually isn't too problematic as that layer is deleted when the job exits, but this is not the case for you due to the bug above.

We have work in progress to change this behaviour (#3100) so that slugs are only downloaded once per host (rather than once per job), and be SquashFS fileysystems (rather than gzipped tarballs which need to be extracted) which will benefit from being mounted once and cached by the kernel file cache, dramatically improving the time it takes to spin up jobs.

**Comment by lmars** [comment] 2016-09-16 15:08
P.S. the patch I intend to make is to use the closing of the RPC socket to indicate that the container has died (we can't use `wait(2)` because `flynn-host` is not always the parent, e.g. after an update or hard restart), and also wrap the AUFS cleanup in a retry in case the socket closes unexpectedly before the container dies.

I'll also dig into the libcontainer code to see if a hook exists for this purpose.

**Comment by benkaiser** [comment] 2016-09-17 01:20
Thanks @lmars for the detailed response,

What you said about why it can't be cleaned up makes sense, a patch for that would be really nice :+1: 

That sounds like a really good PR, and looking at the size of it, it's huge!
Any idea on timeline for when that will get merged? does someone else have to review and approve it before then?

**Comment by lmars** [comment] 2016-09-17 11:52
@benkaiser yep that PR is pretty big so, although the work is pretty much done, I'll be merging it in separate pull requests (starting with #3381). I hope to have it merged within a week or two, so it will appear in October's stable release.

**Comment by benkaiser** [comment] 2016-09-17 12:02
Fantastic!

I'm going to give Dokku a shot in the meantime to see how well it deals with the disk usage (I only have one host so Dokku seems to fit my use case too), but I do really love the flynn way of doing everything (having a client cli and all).

**Comment by lmars** [comment] 2016-09-17 12:33
@benkaiser ok so I took another look at the bug and my previous reasoning was incorrect, I actually think this is a race which only happens on low spec machines, what is the spec of your host (CPU / RAM)?

**Comment by lmars** [comment] 2016-09-17 13:27
@benkaiser I now believe I have identified the issue, to verify could you possibly gist the output of `dmesg | grep aufs`?

My current thinking is that you are encountering the AUFS related error mentioned in #2044, which we fixed by [trying to mount the AUFS mount multiple times](https://github.com/flynn/flynn/pull/2272), but then I think this leaves multiple mounts which all need to be unmounted, but Flynn is only unmounted one of them, leading to the `EBUSY` error. If this is correct, wrapping the cleanup in a retry should fix it.

Sorry for the back and forward, I'm confident this is the issue and we can push a fix today.

**Comment by benkaiser** [comment] 2016-09-17 13:48
@lmars it's the entry-level linode size: https://www.linode.com/pricing
2GB RAM / 24GB storage.

I can gist that output, you might have to trawl back a bit in the gist though as I've since nuked the Flynn install and setup Dokku. Not at my machine presently so I'll upload it when I get home.

Thanks for your attention to this issue

**Comment by benkaiser** [comment] 2016-09-17 14:08
I think at some point while trying to clear up space I rebooted, so the only output of `dmesg | grep aufs` was:

```
root@ubuntu:~# dmesg | grep aufs
[    3.381342] aufs 3.13-20140303
[    4.089368] aufs au_opts_parse:1155:flynn-host[2113]: unknown option dirperm1
[  640.054269] aufs au_opts_parse:1155:flynn-host[4242]: unknown option dirperm1
[ 1559.872523] aufs au_opts_parse:1155:flynn-host.v201[5941]: unknown option dirperm1
[ 3026.287597] aufs au_opts_parse:1155:dockerd[9787]: unknown option dirperm1
```

I found some more logs in a slightly older (~2 days) syslog, around when I set up the most recent flynn cluster:

```
# cat /var/log/syslog.1 | grep aufs
Sep 16 09:18:16 ubuntu kernel: [69919.355118] aufs au_opts_parse:1155:flynn-host[11323]: unknown option dirperm1
Sep 16 09:33:11 ubuntu kernel: [70814.900591] aufs au_opts_parse:1155:flynn-host[13993]: unknown option dirperm1
Sep 16 09:35:07 ubuntu kernel: [70930.511096] aufs opt_add:736:flynn-host[14065]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.572638] aufs opt_add:736:flynn-host[14065]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.641218] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.698268] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.755279] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.810158] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.865009] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.919748] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70930.974837] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70931.029732] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70931.084684] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:07 ubuntu kernel: [70931.139575] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.194537] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.249586] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.304647] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.359281] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.414283] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:35:08 ubuntu kernel: [70931.469136] aufs opt_add:736:flynn-host[14709]: lookup failed /var/lib/docker/aufs/diff/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83 (-2)
Sep 16 09:40:53 ubuntu kernel: [71276.681543] aufs au_opts_parse:1155:flynn-host[15596]: unknown option dirperm1
Sep 16 10:16:03 ubuntu kernel: [73386.904693] aufs au_opts_parse:1155:flynn-host.v201[20785]: unknown option dirperm1
```

Hope that helps, let me know if you'd like any more output

**Comment by lmars** [comment] 2016-09-18 20:30
@benkaiser I have been unable to reproduce this issue, and I don't think my proposed fix of retrying the unmount of the AUFS layer will fix this.

When I last tried Linode, they defaulted to their own kernel, so did you manually switch to a stock Ubuntu kernel? I am wondering if this is a bug in the kernel you are running.

**Comment by benkaiser** [comment] 2016-09-18 22:52
Okay, fair enough.

Yes I followed the procedure to install the stock ubuntu kernel (then updated grub, then rebooted and confirmed it was on the stock kernel).

```
$ uname -a
Linux ubuntu 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lmars** [comment] 2016-11-04 16:38
We have now switched away from AUFS (#3619) so this is no longer an issue.

**Closed by lmars** 2016-11-04 16:38 UTC
Labels: component/host, kind/bug
