### ISSUE TITLE
Making an postgres route external?

### ISSUE THREAD

**Issue by mphuie** [flynn/flynn#3570] opened 2016-10-24 21:47 UTC
How do I add an external route for postgres?  When I created the instance, I was able to connect to postgres externally.  Now for some reason I'm not able to (my scripts to load data into the DB now fail) In the dashboard, it seems like it's internal only (as clicking the button doesn't switch to external).  

I have another cluster setup with same apps and postgres can be connected externally.  Is there a setting I'm missing somewhere?

**Comment by michaelyork** [comment] 2016-10-24 23:03
On the resource's page, where you have the "internal/external" toggle, add "/create-external-route" to the end of the URL. This will allow you to generate a new external route and re-enable that toggle.

Agreed, this should have a shortcut.

**Comment by mphuie** [comment] 2016-10-25 01:51
Awesome thanks for the quick reply, is there a corresponding CLI command?  I was playing with a bunch of variations of `flynn route` with no luck either

**Comment by josephglanville** [comment] 2016-10-25 07:14
I believe the equivalent CLI command is `flynn -a postgres route add tcp --service postgres --leader`.

However you should first check if a route exists with `flynn -a postgres route`, the output will be empty if an external route hasn't been created, otherwise you should see something like this:
```
flynn -a postgres route
ROUTE     SERVICE   ID                                        STICKY  LEADER  PATH
tcp:3010  postgres  tcp/ab755c87-f6a4-40c1-bb16-1ce81612ffb3          true
```

The number following `tcp`, in this case `3010` is the port you can connect to PostgreSQL externally with.

**Comment by mphuie** [comment] 2016-10-25 16:22
So adding `/create-external-route` to the resource page seems to work, but if the page is refreshed, external can't be toggled.

**Comment by titanous** [comment] 2016-11-03 15:44
#3574 covers the root cause here, closing.

**Closed by titanous** 2016-11-03 15:44 UTC
Labels: kind/question
