### ISSUE TITLE
flynn export doesn't contain the MariaDB

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2813] opened 2016-05-11 10:53 UTC
Hi,

when I export an application with a provisioned MariaDB, the resulting tarball doesn't contain the database.

**Comment by lmars** [comment] 2016-05-11 20:44
@philiplb it seems to work for me:

```
$ flynn create app1

$ git push flynn master

$ flynn -a app1 resource add mysql
Created resource a84da78d-8d8f-4dc8-a5da-7256b51cd95a and release 0f19833c-2e34-40e9-996b-bba88f2b379a.

$ flynn -a app1 mysql console -- -e "CREATE TABLE foo (bar INT); INSERT INTO foo VALUES (1), (2), (3)"

$ flynn -a app1 export --file backup.tar
7.25 MB 1.03 MB/s 7s

$ tar tf backup.tar 
app1/app.json
app1/routes.json
app1/release.json
app1/artifact.json
app1/formation.json
app1/slug.tar.gz
app1/mysql.dump

$ tar xf backup.tar app1/mysql.dump

$ grep -C2 foo app1/mysql.dump 

--
-- Table structure for table `foo`
--

DROP TABLE IF EXISTS `foo`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `foo` (
  `bar` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
--

--
-- Dumping data for table `foo`
--

LOCK TABLES `foo` WRITE;
/*!40000 ALTER TABLE `foo` DISABLE KEYS */;
INSERT INTO `foo` VALUES (1),(2),(3);
/*!40000 ALTER TABLE `foo` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

```

Can you provide more details as to what issue you are seeing?

**Comment by lmars** [comment] 2016-05-11 22:05
@philiplb importing mysql databases is actually broken, I have proposed a fix in #2818.

**Comment by philiplb** [comment] 2016-05-12 08:51
Ok, cool.
Some more details here:
- added the MySQL database to the app via the dashboard
- populated the database
- deployed the (Java web) application
- ran "flynn -a myApp export -f myApp.tar"
- unpack it and this is now the list of files, containing no mysql.dump:
  - app.json
  - artifact.json
  - formation.json
  - release.json
  - routes.json
  - slug.tar.gz

The version of Flynn on the cluster is v20160327 (still [latest](https://dl.flynn.io/ec2/images.json) from the stable channel I think?), my command line client is v20160512.0, just updated it via

```bash
L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
```

**Comment by lmars** [comment] 2016-05-12 15:51
@philiplb ok I can't reproduce using the versions you stated. Does the exported `release.json` file include mysql related variables? I would expect something like this:

```
$ jq .env app/release.json 
{
  "DATABASE_URL": "mysql://4b8f55c2026f21c3be157489ed2f0d19:7cdb298dff3ebab978e7964c47c9ce16@leader.mariadb.discoverd:3306/03d79da3d35fd1857ebb8dc979216e1d",
  "FLYNN_MYSQL": "mariadb",
  "MYSQL_DATABASE": "03d79da3d35fd1857ebb8dc979216e1d",
  "MYSQL_HOST": "leader.mariadb.discoverd",
  "MYSQL_PWD": "7cdb298dff3ebab978e7964c47c9ce16",
  "MYSQL_USER": "4b8f55c2026f21c3be157489ed2f0d19",
  "SLUG_URL": "http://blobstore.discoverd/60eb922e-8e11-4799-9e9a-60a9917c4073.tgz"
}
```

**Comment by philiplb** [comment] 2016-05-12 15:55
@lmars 
No, just those two I set via the dashboard:

>    "APP_PATH": "/",
>    "MAVEN_CUSTOM_OPTS": "..."

And one Flynn internal:

>    "SLUG_URL": "http://blobstore.discoverd/dfe9da5b-0729-475b-b965-f3666ec571af.tgz"

**Comment by lmars** [comment] 2016-05-12 15:58
@philiplb ok, so it looks like the app does not have a mysql database provisioned so something has gone wrong there.

When you say you "populated the database", how did you do that?

**Comment by philiplb** [comment] 2016-05-12 16:04
The database shows properly up on the applications page.
Populated: After provisioning, I connected via [Adminer](http://adminer.org/) to it and imported a SQL dump file.

**Comment by josephglanville** [comment] 2016-05-12 16:46
Something seems to have gone wrong associating the app with the databsae instance. Can you describe the exact steps taken to create the database and link the application to it if you did not use `flynn resource add mysql`?

**Comment by philiplb** [comment] 2016-05-12 17:17
I ran

```bash
flynn create myapp
```

went to the dashboard and clicked the button "Provision database". There I selected MySQL and clicked "Provision database". Now the dialog is stuck with a grayed out button "Provision database".
From Firebug:

> "NetworkError: 404 Not Found - https://controller.flynn.abc.com/apps/367a6a6a-c8ef-47f1-b7c1-f3b4ba56c5c9/release"

It seems to expect a release before adding the env vars?

**Comment by jvatic** [comment] 2016-05-12 17:37
@philiplb It looks like you've encountered a dashboard bug, to work around the issue you'll need to create a release (e.g. `flynn release add "http://example.com"` or `flynn env set FOO=BAR`).

**Comment by lmars** [comment] 2016-05-12 22:28
@jvatic so is that the cause of this issue? Should we close this now #2821 is merged?

**Comment by jvatic** [comment] 2016-05-13 01:26
@lmars it appears so. Though I came across another issue: `flynn export` fails when the app hasn't been deployed (`error retrieving artifact: GET https://controller.1.localflynn.com/artifacts/: httpclient: raw req: unexpected status 401`)

**Closed by jvatic** 2016-05-13 01:26 UTC
Labels: cli, question
