### ISSUE TITLE
Docker images are not garbage collected

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#3314] opened 2016-08-19 19:57 UTC
Following up from https://github.com/flynn/flynn/issues/3163#issuecomment-241102357.

We're running Flynn, v20160726.0, which I think was from before #38 (etc) got fixed, and our /var/lib/docker/aufs folder is quite overgrown, which has caused our machine to completely run out of space. 

The cleanup script is not working, either, for reasons detailed in the above link.

Any suggestions?

**Comment by titanous** [comment] 2016-08-19 19:59
v20160726.0 has that leak fixed. How much space is consumed by `/var/lib/docker/aufs`?

**Comment by brettneese** [comment] 2016-08-19 20:06
Doing a du right now on the whole directory, but I know based on my
colleague @mnaughto that ```diff``` is taking up around 45GB.

**Comment by brettneese** [comment] 2016-08-19 20:07
And apparently the whole thing is taking up "about 60GB"

**Comment by titanous** [comment] 2016-08-19 20:07
How many containers are running on the host?

**Comment by titanous** [comment] 2016-08-19 20:09
And how many directories in the `diff` dir start with `tmp-` or end with `-init`?

**Comment by brettneese** [comment] 2016-08-19 20:09
flynn-host ps lists around 25 including Flynn's own

**Comment by brettneese** [comment] 2016-08-19 20:13
38 tmp- files out of 889 total and 0 that end in -init.

On Aug 19, 2016 3:09 PM, "Brett Neese" <brneese@brneese.com> wrote:

flynn-host ps lists around 25 including Flynn's own

**Comment by titanous** [comment] 2016-08-19 20:15
Are you using Docker to deploy apps?

**Comment by brettneese** [comment] 2016-08-19 20:15
Other thing is that disk usage over time has grown in a fairly consistent
way:

**Comment by brettneese** [comment] 2016-08-19 20:17
Yes

**Comment by brettneese** [comment] 2016-08-19 20:21
We've tried to cleanup old docker images ie http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/, but there's no docker daemon on the host (at least in the path).

**Comment by titanous** [comment] 2016-08-19 20:24
It looks like we currently have no garbage collection for custom Docker images, so what's happening is the layers are getting unpacked for each deploy and never cleaned up when new releases are created. We're in the process of redoing our image management system, and this will be fixed.

I'm investigating the best way to detect images that are not in use, if you can start a new cluster that would be the fastest fix.

**Comment by brettneese** [comment] 2016-08-19 20:28
Is there any other stop-gap solution? We're working on being able to automate a redeployment of a new cluster but until then starting a new cluster is a little more involved than we'd like. (We have to do a manual install because the installer currently doesn't have the options to deploy with the correct vpc/and other options we need.)

**Comment by titanous** [comment] 2016-08-19 20:33
I'll have to write a tool to do cleanup, available tomorrow at the latest.

**Comment by brettneese** [comment] 2016-08-19 20:37
😍

Thanks, you rock.

**Comment by temujin9** [comment] 2016-08-27 01:36
Initial results with the gc tool aren't terribly promising: nodes that were at 90% disk usage only lost about 1% usage. Will retry on fresh clusters anyway, but please note if you update this cleanup tool.

**Comment by titanous** [comment] 2016-08-27 01:42
@temujin9 Did you identify Docker images as the root cause of the disk usage (eg. `/var/lib/docker`)

**Comment by temujin9** [comment] 2016-08-27 01:57
Yep.

**Comment by temujin9** [comment] 2016-08-27 01:58
My teammate is (hopefully) collecting the debug logs for that now . . .

**Comment by temujin9** [comment] 2016-09-01 02:08
Ran into an issue with the `gc` code linked above. The new cluster running it hourly stopped accepting `git pushes` at some point: it appears to have killed the slugbuilder container..

https://gist.github.com/d35a09b3fc70ff7529993fec002a5328 and https://gist.github.com/6ccbdfae52ddb27f814f8b804cadc383 are the gists that didn't 405.

**Comment by mnaughto** [comment] 2016-10-06 19:56
Found an additional docker-related storage issue. Docker really likes chewing up "inodes", it seems. We had this issue on our build server and it appears to be a problem on our production flynn server as well:

    $ df -i
    Filesystem      Inodes   IUsed   IFree IUse% Mounted on
    udev           1019277     411 1018866    1% /dev
    tmpfs          1021954     357 1021597    1% /run
    /dev/xvda1     3276800 3273467    3333  100% /
    none           1021954      16 1021938    1% /sys/fs/cgroup
    none           1021954       1 1021953    1% /run/lock
    none           1021954      82 1021872    1% /run/shm
    none           1021954       3 1021951    1% /run/user
    none           3276800 3273467    3333  100% /var/lib/docker/aufs/mnt/tmp-ip1723153135-c1f80bac-71aa-4991-8fdd-4b1ed9d0a587
    ....

I found out about this issue after reading through https://github.com/docker/docker/issues/10613. Seems like running `docker volume rm $(docker volume ls -qf dangling=true)` will bandage it, but since there's no `docker` available on the path within a flynn host, I'm not really sure how to accomplish such a feat. Moreover, it seems like the more reliable way to work around this problem comes when you're first defining the file systems. 

As it stands, every docker deployment now results in `no space left on device`, even though it seems like the deployment goes through successfully, though I'm not sure that's the case, actually.

Any idea what we might be able to do to work around this? Can we fix the issue without spinning up a new flynn instance?

**Comment by lmars** [comment] 2016-10-09 14:31
@mnaughto we are switching away from AUFS and implementing full image garbage collection (see #3100) which we plan to merge soon.

Using the `docker` CLI will most likely not work because Flynn manages its own images, and it is incompatible with recent versions of Docker (see #2459).

Did you try running the GC script linked above? If so, and it doesn't clean up any space, then I would suggest booting a new cluster and waiting for the new image format + GC to be merged.

**Comment by lmars** [comment] 2018-01-07 20:27
Flynn no longer extracts Docker images into `/var/lib/docker/aufs`, closing.

**Closed by lmars** 2018-01-07 20:27 UTC
Labels: component/host, kind/bug
