### ISSUE TITLE
Scheduler wasn't running properly after replacing a node

### ISSUE THREAD

**Issue by ohhatiya** [flynn/flynn#3326] opened 2016-08-25 00:15 UTC
We had a cluster where a node died. Shortly after its replacement came online, the scheduler stopped running. Then it stopped running on all the other hosts.

Here's a Gist with debug info from one of the hosts:
https://gist.github.com/85f28835546bdba808681933644b3236

And tarballs for the others:
https://bazaarvoice.box.com/s/972dnf2p692m40rwwvn6kks3ear0ihfr
https://bazaarvoice.box.com/s/cl983chbpg6v6m0l86fx9vq63gzch5hv
https://bazaarvoice.box.com/s/fvm5sukewaf82kmp7uz6ujkm5mnteeqo
https://bazaarvoice.box.com/s/xsaf06vwnuma1uziimnafcqal7l4vblk

**Comment by lmars** [comment] 2016-08-25 13:18
This looks like the issue I though was fixed by 90495f3, I will investigate some more.

**Comment by lmars** [comment] 2016-08-25 20:23
Ok the cause here is one of the issues mentioned in #3324 (namely `RunPutJobs` blocking if a single job cannot be persisted, not reading from `s.putJobs` and thus blocking any calls to `s.persistJob`).

I have a fix coming soon.

**Closed** 2016-08-26 22:47 UTC
Labels: component/scheduler, kind/bug
