### ISSUE TITLE
Disconnecting from an interactive `flynn run` process should send EOF

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1429] opened 2015-04-08 23:26 UTC
I'm not sure how to handle this correctly, but I have several zombie `redis-cli` processes due to disconnection. The only way to terminate them at this point is to `flynn kill` them.

**Comment by titanous** [comment] 2015-04-09 00:28
This is a duplicate of #436.

**Closed by titanous** 2015-04-09 00:28 UTC
