### ISSUE TITLE
Invalid route

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#4417] opened 2018-08-01 11:26 UTC
I cannot add domains to any apps via dashboard. it works via cli though

<img width="531" alt="screen shot 1397-05-10 at 15 49 33" src="https://user-images.githubusercontent.com/589808/43518870-a4645994-95a2-11e8-9569-f89689dff8fe.png">

**Comment by jvatic** [comment] 2018-08-01 17:07
Duplicate of #4407

**Closed by jvatic** 2018-08-01 17:07 UTC
