### ISSUE TITLE
host: "max concurrent AddJobs calls" during restore

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2650] opened 2016-03-31 20:41 UTC
```
19:49:33.856518 run-app controller
19:49:36.153077 run-app controller error: ratelimited: maximum concurrent AddJob calls running, try again later'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
++ flynn-host collect-debug-info
+ debug_info='t=2016-03-31T20:02:32+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2016-03-31T20:02:32+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2016-03-31T20:02:32+0000 lvl=info msg="getting flynn-host logs"
t=2016-03-31T20:02:32+0000 lvl=info msg="getting job logs"
t=2016-03-31T20:02:34+0000 lvl=info msg="getting system information"
t=2016-03-31T20:02:47+0000 lvl=info msg="creating anonymous gist"
t=2016-03-31T20:02:48+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/8d6559235345cf775ed3e2c56bc46fb9"'
```

**Comment by titanous** [comment] 2016-03-31 20:42
Duplicate of #2650.

**Closed by titanous** 2016-03-31 20:42 UTC

**Comment by temujin9** [comment] 2016-03-31 20:47
Whup, sorry about that.
