### ISSUE TITLE
Cryptic failures in gitreceive

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1811] opened 2015-09-03 01:03 UTC
```
t=2015-09-03T00:11:06+0000 lvl=info msg="request started" component=gitreceive req_id=7262d879-9b53-4c6a-9243-3ddf6bbe7484 method=GET path=/conv-integration-teamcity-radiator.git/info/refs client_ip=10.100.18.17
t=2015-09-03T00:11:06+0000 lvl=info msg="request completed" component=gitreceive req_id=7262d879-9b53-4c6a-9243-3ddf6bbe7484 status=401 duration=81.376µs
t=2015-09-03T00:11:07+0000 lvl=info msg="request started" component=gitreceive req_id=7a96b64f-0709-4036-988f-83f3a431b696 method=GET path=/conv-integration-teamcity-radiator.git/info/refs client_ip=10.100.18.17
t=2015-09-03T00:11:07+0000 lvl=info msg="request completed" component=gitreceive req_id=7a96b64f-0709-4036-988f-83f3a431b696 status=401 duration=78.468µs
t=2015-09-03T00:11:07+0000 lvl=info msg="request started" component=gitreceive req_id=eb21c0f2-3bcd-4340-995f-6a5e7bbe58dd method=GET path=/conv-integration-teamcity-radiator.git/info/refs client_ip=10.100.18.17
t=2015-09-03T00:11:08+0000 lvl=info msg="request completed" component=gitreceive req_id=eb21c0f2-3bcd-4340-995f-6a5e7bbe58dd status=200 duration=640.165189ms
t=2015-09-03T00:11:08+0000 lvl=info msg="request started" component=gitreceive req_id=06c8cef2-174f-4cec-b735-03eee9951eea method=POST path=/conv-integration-teamcity-radiator.git/git-receive-pack client_ip=10.100.18.17
t=2015-09-03T00:11:08+0000 lvl=info msg="request completed" component=gitreceive req_id=06c8cef2-174f-4cec-b735-03eee9951eea status=200 duration=33.214589ms
t=2015-09-03T00:11:08+0000 lvl=info msg="request started" component=gitreceive req_id=258cc2da-8013-4aab-ba07-f1aa1ea3b7fc method=POST path=/conv-integration-teamcity-radiator.git/git-receive-pack client_ip=10.100.18.17
t=2015-09-03T00:11:08+0000 lvl=eror msg="handlePostRPC write to subprocess" component=gitreceive req_id=258cc2da-8013-4aab-ba07-f1aa1ea3b7fc error="write |1: broken pipe"
t=2015-09-03T00:11:08+0000 lvl=info msg="request completed" component=gitreceive req_id=258cc2da-8013-4aab-ba07-f1aa1ea3b7fc status=500 duration=284.103863ms
t=2015-09-03T00:51:50+0000 lvl=info msg="request started" component=gitreceive req_id=e8bde48d-56dc-4091-8faa-a97cac3ebe6d method=HEAD path=/ client_ip=10.100.18.17
````

Only appears to happen on some pushes; my initial application still pushes just fine. https://gist.github.com/7853e4cc14f8dc80b343 has the full debug info from the cluster.

**Comment by titanous** [comment] 2015-09-03 01:04
Are there any errors on the client side when this appears in the log?

**Comment by temujin9** [comment] 2015-09-03 01:06
```
Publishing doula to flynn-ci-us-east-1.nexus.bazaarvoice.com
Counting objects: 9002, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3017/3017), done.
Writing objects: 100% (9002/9002), 1.28 MiB | 87.00 KiB/s, done.
Total 9002 (delta 4003), reused 8904 (delta 3933)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

**Comment by temujin9** [comment] 2015-09-03 01:08
Reproduces on every cluster.

**Comment by titanous** [comment] 2015-09-03 01:09
This looks like a dupe of #1799. Is it a specific repo that is failing every time?

**Comment by temujin9** [comment] 2015-09-03 01:10
It appears to be consistent across repo and endpoint, let me check some others.

**Comment by temujin9** [comment] 2015-09-03 01:25
Yep: same failure for this repo against all endpoints. Trying out another repo, so far not getting it anywhere with that one.

**Comment by titanous** [comment] 2015-09-03 01:33
K, I'm going to try to track down a few larger OSS repos to try out (we haven't seen this for any of our example apps), if you can come up with any commonalities between failing repos or can provide me with an example repo that fails it would be really helpful.

**Comment by temujin9** [comment] 2015-09-03 01:49
Unfortunately, my instance of this is from a private repo. I'll talk with the team it comes from in the morning, see if they have any objection to giving you access to a copy.

**Comment by titanous** [comment] 2015-09-03 01:53
I now have a repro case, I'm going to close this as a dupe of #1799 since the error messages on both sides are exactly the same.

**Closed by titanous** 2015-09-03 01:53 UTC

**Comment by temujin9** [comment] 2015-09-03 01:58
Hmm. Not sure if this is related, but it's in a similar place, and is easy to reproduce:
```
t=2015-09-03T01:50:35+0000 lvl=info msg="request started" component=gitreceive req_id=69388fc3-2722-4764-bb87-e38d0cac19d9 method=GET path=/conv-integration-teamcity-radiator.git/info/refs client_ip=10.100.17.151
t=2015-09-03T01:50:35+0000 lvl=eror msg="handleGetInfoRefs wait for subprocess" component=gitreceive req_id=69388fc3-2722-4764-bb87-e38d0cac19d9 error="exit status 128"
t=2015-09-03T01:50:35+0000 lvl=info msg="request completed" component=gitreceive req_id=69388fc3-2722-4764-bb87-e38d0cac19d9 status=200 duration=8.001935ms
```
and from the CLI
```
Publishing upstreamtest-teamcity-radiator to flynn-ci-us-east-1.nexus.bazaarvoice.com
fatal: protocol error: bad line length character: fata
```

I can also reproduce the first error with this one's open source predecessor: https://github.com/gogobot/teamcity-radiator

**Comment by titanous** [comment] 2015-09-03 02:01
I believe this error happens on the second push after the initial 500 error. I can now reliably reproduce both errors, so I'm working on tracking down the cause.

**Comment by temujin9** [comment] 2015-09-03 02:03
Good to hear. Let me know if I can help.
