### ISSUE TITLE
 The MariaDB server is running with the --read-only option so it cannot execute this statement

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4382] opened 2018-05-05 20:30 UTC
Hi,

I'm getting this error when running:

flynn -a AppName mysql restore -f wp-data/dbdump.sql

**The MariaDB server is running with the --read-only option so it cannot execute this statement**

I'm not sure what to do with this... can you help figure out what's going wrong?

**Comment by philiplb** [comment] 2018-05-06 21:43
Maybe a similar issue to our trouble with it:
https://github.com/flynn/flynn/issues/3894
https://github.com/flynn/flynn/issues/4144

**Comment by SalvoLunar** [comment] 2018-05-07 10:30
It was a space issue, I've removed the cluster and recreated it on instances with bigger specs and it worked fine.

How do you check the space available on the cluster?

**Comment by SalvoLunar** [comment] 2018-05-29 10:36
Hi there,
this issue is appearing again after a server reboot.
if I try to collect the logs I get this error:

root@scw-b75f3d:~# sudo flynn-host collect-debug-info
INFO[05-29|10:30:22] uploading logs and debug information to a private, anonymous gist 
INFO[05-29|10:30:22] this may take a while depending on the size of your logs 
INFO[05-29|10:30:22] getting flynn-host logs 
INFO[05-29|10:30:22] getting sirenia metadata 
INFO[05-29|10:30:22] getting scheduler state 
INFO[05-29|10:30:22] getting job logs 
INFO[05-29|10:33:19] getting system information 
INFO[05-29|10:33:21] creating anonymous gist 
198.59 MB / 198.59 MB [=================================] 100.00 % 29.11 MB/s 0sEROR[05-29|10:33:28] unexpected HTTP status: 401 
198.59 MB / 198.59 MB [=================================] 100.00 % 28.58 MB/s 6s
10:33:28.807757 host.go:166: unexpected HTTP status: 401

I'm not even sure this is a space issue because my blobstore has been migrated to S3.
How can I debug this?

Thanks,
Salvo

**Comment by SalvoLunar** [comment] 2018-06-27 18:35
So this is happening again.

Suddenly MariaDB is running with the --read-only option and I'm not sure how to fix that.
I've tryed using flynn-host fix but that stopped at  _waiting for cluster to come up read-write fn=FixSirenia_

Is the only option here to bring down the cluster and recreate it from a backup?

Would you have any suggestions?

Thanks,
Salvo

**Comment by SalvoLunar** [comment] 2018-06-30 09:12
The same error happened this morning, it's completely random and I cannot pinpoint the cause of it.

I had to restore the entire cluster again...

**Comment by SalvoLunar** [comment] 2018-08-08 15:41
Hi there,

So this issue is still happening, after a month of things running smoothly I discovered today that in the early morning one of the MariaDB workers had crashed.

My client called me saying that some of the content published yesterday had disappeared from the website.

I checked the Flynn Dashboard and Mysql was still running, there was a new process started this morning and some old one from 23 days ago still running.

I believe the replication somehow stopped working and the 23 days old worker didn't have all content published yesterday or before that.

I tried to restart all workers and everything is now not working.

If I try to run any operation I get the usual :

**The MariaDB server is running with the --read-only option so it cannot execute this statement**

This is a snippet of the logs from one of the workers:
```
[2018-08-08T15:31:14.829162Z]    t=2018-08-08T15:31:14+0000 lvl=info msg=status app=mariadb fn=waitForUpstream upstream=XXX.XXX.XX.XX:3306 upstream_http_addr=XXX.XXX.XX.XX:3307 running=false xlog= user_exists=false
[2018-08-08T15:31:15.813055Z]    t=2018-08-08T15:31:15+0000 lvl=eror msg="upstream did not come online in time" app=mariadb fn=waitForUpstream upstream=XXX.XXX.XX.XX:3306 upstream_http_addr=XXX.XXX.XX.XX:3307
[2018-08-08T15:31:15.813232Z]    t=2018-08-08T15:31:15+0000 lvl=eror msg="error applying database config" app=mariadb component=peer fn=applyConfig err="upstream is offline"
[2018-08-08T15:31:15.813329Z]    t=2018-08-08T15:31:15+0000 lvl=dbug msg="at rest" app=mariadb component=peer fn=rest
```
I cannot access the wordpress backend anymore and I will need to restore the whole cluster with a 2 days old backup tomorrow early morning.

If there is a way to fix this in the meantime please help.

Thanks,
Salvo

**Comment by ronalddas** [comment] 2019-01-14 20:20
> Hi there,
> this issue is appearing again after a server reboot.
> if I try to collect the logs I get this error:
> 
> root@scw-b75f3d:~# sudo flynn-host collect-debug-info
> INFO[05-29|10:30:22] uploading logs and debug information to a private, anonymous gist
> INFO[05-29|10:30:22] this may take a while depending on the size of your logs
> INFO[05-29|10:30:22] getting flynn-host logs
> INFO[05-29|10:30:22] getting sirenia metadata
> INFO[05-29|10:30:22] getting scheduler state
> INFO[05-29|10:30:22] getting job logs
> INFO[05-29|10:33:19] getting system information
> INFO[05-29|10:33:21] creating anonymous gist
> 198.59 MB / 198.59 MB [=================================] 100.00 % 29.11 MB/s 0sEROR[05-29|10:33:28] unexpected HTTP status: 401
> 198.59 MB / 198.59 MB [=================================] 100.00 % 28.58 MB/s 6s
> 10:33:28.807757 host.go:166: unexpected HTTP status: 401
> 
> I'm not even sure this is a space issue because my blobstore has been migrated to S3.
> How can I debug this?
> 
> Thanks,
> Salvo

Hey, Even I have the same issue.
`0 B / 137.84 MB [------------------------------------------------------] 0.00 % INFO[01-14|20:11:41] creating anonymous gist
137.84 MB / 137.84 MB [==================================] 100.00 % 4.48 MB/s 0sEROR[01-14|20:12:15] unexpected HTTP status: 401
137.84 MB / 137.84 MB [=================================] 100.00 % 4.08 MB/s 33s
`
I think this is because of the large file size (100MB+, github has a strict file limit of 100MB's), so its not able to upload it to a gist. They should have an option to save it the debug-info locally

**Comment by philiplb** [comment] 2019-11-13 15:42
Closing as duplicate of #4144 .

**Comment by titanous** [comment] 2021-02-18 21:57
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

**Closed by titanous** 2021-02-18 21:57 UTC
