### ISSUE TITLE
"ERROR:  cannot execute XXX in a read-only transaction" during restore from backup

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2587] opened 2016-03-16 20:57 UTC
```
++ flynn-host bootstrap --peer-ips=10.100.47.226,10.100.39.201,10.100.41.193 --from-backup /mnt/flynn-restore-source --timeout 1200
+ bootstrap_output='20:22:48.211367 check online-hosts
20:22:48.219524 run-app discoverd
20:23:30.796661 run-app flannel
20:23:32.016760 wait-hosts wait-hosts
20:23:34.031541 run-app postgres
20:24:31.041414 wait postgres-wait
20:24:36.281487 restore-postgres restore
SET
SET
SET
ERROR:  cannot execute DROP DATABASE in a read-only transaction
ERROR:  cannot execute DROP DATABASE in a read-only transaction
ERROR:  cannot execute DROP DATABASE in a read-only transaction
ERROR:  cannot execute DROP ROLE in a read-only transaction
ERROR:  cannot execute DROP ROLE in a read-only transaction
ERROR:  cannot execute DROP ROLE in a read-only transaction
ERROR:  cannot execute DROP ROLE in a read-only transaction
ERROR:  cannot execute DROP ROLE in a read-only transaction
ERROR:  cannot execute CREATE ROLE in a read-only transaction
ERROR:  cannot execute ALTER ROLE in a read-only transaction
ERROR:  cannot execute CREATE ROLE in a read-only transaction
ERROR:  cannot execute ALTER ROLE in a read-only transaction
ERROR:  cannot execute CREATE ROLE in a read-only transaction
ERROR:  cannot execute ALTER ROLE in a read-only transaction
ERROR:  cannot execute CREATE ROLE in a read-only transaction
ERROR:  cannot execute ALTER ROLE in a read-only transaction
ERROR:  cannot execute CREATE ROLE in a read-only transaction
ERROR:  cannot execute ALTER ROLE in a read-only transaction
ERROR:  cannot execute CREATE DATABASE in a read-only transaction
ERROR:  cannot execute CREATE DATABASE in a read-only transaction
ERROR:  cannot execute CREATE DATABASE in a read-only transaction
ERROR:  cannot execute REVOKE in a read-only transaction
ERROR:  cannot execute REVOKE in a read-only transaction
ERROR:  cannot execute GRANT in a read-only transaction
ERROR:  cannot execute GRANT in a read-only transaction
\connect: FATAL:  database "051c5383b32ae3340526e2cb1f07a013" does not exist

20:24:37.206372 restore-postgres restore error: error running psql restore: exec: job exited with status 2 - "SET\nSET\nSET\nERROR:  cannot execute DROP DATABASE in a read-only transaction\nERROR:  cannot execute DROP DATABASE in a read-only transaction\nERROR:  cannot execute DROP DATABASE in a read-only transaction\nERROR:  cannot execute DROP ROLE in a read-only transaction\nERROR:  cannot execute DROP ROLE in a read-only transaction\nERROR:  cannot execute DROP ROLE in a read-only transaction\nERROR:  cannot execute DROP ROLE in a read-only transaction\nERROR:  cannot execute DROP ROLE in a read-only transaction\nERROR:  cannot execute CREATE ROLE in a read-only transaction\nERROR:  cannot execute ALTER ROLE in a read-only transaction\nERROR:  cannot execute CREATE ROLE in a read-only transaction\nERROR:  cannot execute ALTER ROLE in a read-only transaction\nERROR:  cannot execute CREATE ROLE in a read-only transaction\nERROR:  cannot execute ALTER ROLE in a read-only transaction\nERROR:  cannot execute CREATE ROLE in a read-only transaction\nERROR:  cannot execute ALTER ROLE in a read-only transaction\nERROR:  cannot execute CREATE ROLE in a read-only transaction\nERROR:  cannot execute ALTER ROLE in a read-only transaction\nERROR:  cannot execute CREATE DATABASE in a read-only transaction\nERROR:  cannot execute CREATE DATABASE in a read-only transaction\nERROR:  cannot execute CREATE DATABASE in a read-only transaction\nERROR:  cannot execute REVOKE in a read-only transaction\nERROR:  cannot execute REVOKE in a read-only transaction\nERROR:  cannot execute GRANT in a read-only transaction\nERROR:  cannot execute GRANT in a read-only transaction\n\\connect: FATAL:  database \"051c5383b32ae3340526e2cb1f07a013\" does not exist\n"'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
++ flynn-host collect-debug-info
+ debug_info='t=2016-03-16T20:24:37+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2016-03-16T20:24:37+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting flynn-host logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting job logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting system information"
t=2016-03-16T20:24:37+0000 lvl=info msg="creating anonymous gist"
t=2016-03-16T20:24:38+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/bcb5d2ce9bcc01586343"'
++ grep -o 'https://gist.github.com/.*'
++ echo 't=2016-03-16T20:24:37+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2016-03-16T20:24:37+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting flynn-host logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting job logs"
t=2016-03-16T20:24:37+0000 lvl=info msg="getting system information"
t=2016-03-16T20:24:37+0000 lvl=info msg="creating anonymous gist"
t=2016-03-16T20:24:38+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/bcb5d2ce9bcc01586343"'
+ gist='https://gist.github.com/bcb5d2ce9bcc01586343"'
```

Looks like a race between standing up the postgres server and starting the backup?

**Comment by titanous** [comment] 2016-03-18 17:39
@josephglanville Please take a look at this when you have a minute.

**Comment by josephglanville** [comment] 2016-03-18 18:36
I looked into this and it's not a race because we introduce the `postgres-wait` step before executing `restore-postgres`. What happened here is the primary lost downstream sync during the restore resulting in the database becoming read-only.

I'm not sure what more we can do here except maybe retrying the restore?

**Comment by josephglanville** [comment] 2016-03-18 18:40
Looks like I initially misread, we actually had the original primary become deposed and the sync take over, once that happened though the sync actually allows connections before it becomes read-write.

**Comment by titanous** [comment] 2016-03-22 00:39
@josephglanville Is there a bug here? I wonder if this was caused by #2618?

**Comment by josephglanville** [comment] 2016-03-22 12:32
I think you are right. Moving to close this one as the likely root cause is #2618 and any work we do to further address heartbeats and registration will also help here.

**Closed by josephglanville** 2016-03-22 12:32 UTC
