### ISSUE TITLE
Restoring cluster from backup partially fails (migrate docker artifacts fails)

### ISSUE THREAD

**Issue by mhlz** [flynn/flynn#3763] opened 2016-12-13 15:36 UTC
I'm trying to restore a cluster from our develop environment that included some docker images (2 of our apps and the official rabbitmq docker image).

    16:22:40.770709 check online-hosts
    16:22:40.771775 run-app discoverd
    16:22:40.867647 run-app flannel
    16:22:40.941062 wait-hosts wait-hosts
    16:22:42.943942 run-app postgres
    16:22:43.291311 sirenia-wait postgres-wait
    16:22:44.405810 restore-postgres restore
    16:22:48.306073 run-app controller
    16:22:48.529085 wait-controller wait-controller
    16:22:48.591750 run-app mariadb
    16:22:48.953570 sirenia-wait mariadb-wait
    16:22:59.245710 restore-mariadb restore
    16:23:08.731669 run-app mongodb
    16:23:09.160918 sirenia-wait mongodb-wait
    16:23:11.028722 restore-mongodb restore
    16:23:13.427898 run-app blobstore
    16:23:13.748825 wait blobstore-wait
    16:23:14.414953 migrate-artifacts migrate-artifacts
    16:23:15.116650 migrate-artifacts running slug migrator
    16:23:15.126436 migrate-artifacts converting 16 active slugs to Flynn images
    ....... (everything's looking good here)
    16:24:41.579160 run-app docker-receive
    16:24:41.852040 wait docker-receive-wait
    16:24:42.262335 migrate-artifacts running Docker image migrator
    16:24:42.273564 migrate-artifacts converting 3 active Docker images to Flynn images
    16:24:42.273577 migrate-artifacts converting Docker image 8ba9251a-366a-48f7-b1ee-    df8ea1bf81a9 (1/3)
    16:25:05.937927 migrate-artifacts ERROR: operation not permitted
    16:25:05.938868 migrate-artifacts error converting Docker image 8ba9251a-366a-48f7-b1ee-df8ea1bf81a9 (1/3): exit status 1
    16:25:05.938874 migrate-artifacts error running Docker image migrator: exit status 1
    16:25:06.223084 migrate-artifacts migrate-artifacts error: error migrating Docker images: exec: job exited with status 1

Since I thought this might be an issue with that specific image, I also tried another one which results in the same error.

I also can't push images to the cluster at all:

    d2808f8124fd: Pushed 
    fe4c16cbf7a4: Pushed 
    received unexpected HTTP status: 500 Internal Server Error
    exit status 1

Looking in the logs of docker-receive I find this line:

    2016-12-13T15:15:49.477409Z app[app.blackwidow-078b8dea-e897-4666-a33f-d5567acaaf3e]: time="2016-12-13T15:15:49Z" level=error msg="response completed with error" err.code=UNKNOWN err.detail="error running artifact job: exec: job exited with status 1: ERROR: operation not permitted\n" err.message="unknown error" http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host=docker.develop.acomodeo.com http.request.id=7c48cfbb-825c-4428-af7f-6ec2928d363f http.request.method=PUT http.request.remoteaddr=78.94.60.130 http.request.uri="/v2/ams/manifests/latest" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.27-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \\(darwin\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=33.938158037s http.response.status=500 http.response.written=70 instance.id=c138d9b5-d0cd-4561-9b58-ae73f450920a vars.name=ams vars.reference=latest version=v20161114.0p1 

Which makes me think that those errors are related. The backup was originally from version v20161104.0 and the current Flynn version is v20161114.0p1.

Output from collect-debug-info is here https://gist.github.com/anonymous/0eb4a41bd73e55e112ac172e3267608e

If you need anything else I'd be happy to help.

**Comment by josephglanville** [comment] 2016-12-13 15:39
@mhlz I just pushed a nightly release (`v20161213.1`) with a fix for this issue.
You can install nightly with `--channel nightly` when installing `flynn-host`.

**Comment by mhlz** [comment] 2016-12-13 16:01
Using that version I'm now getting the following error:

    17:00:44.974867 run-app mariadb
    17:00:45.241162 sirenia-wait mariadb-wait
    17:00:45.244169 host.go:161: error updating mariadb formation: validation_error: Requested formation includes process types that do not exist in release. Invalid process types: [mariadb, web]

**Comment by mhlz** [comment] 2016-12-14 08:52
It seems like this error comes up even when doing a clean install, backing up, deleting everything and trying to restore from that backup in the nightly version v20161213.1.

**Comment by josephglanville** [comment] 2016-12-14 11:53
I am unable to reproduce.
Can you provide more details about the cluster the backup is coming from?

**Comment by mhlz** [comment] 2016-12-14 15:11
What I did was:

    CLUSTER_DOMAIN=blabla.com flynn-host bootstrap --min-hosts 1
    flynn cluster backup --file test.tar

Wipe server

    flynn-host bootstrap --from-backup test.tar

This failed with the above error message. It was all done in v20161213.1.

The backup came from version v20161104.0 and is the same with which I tried to restore originally where I had problems with docker. For now I just used v20161104.0 again to do the restore which worked fine.

**Comment by titanous** [comment] 2016-12-21 17:41
@mhlz Can you try again with v20161218.1? We've fixed some migration issues recently that might have caused this.

**Comment by titanous** [comment] 2017-01-03 16:34
Closing due to lack of feedback, please open a new issue if you're still having trouble with the latest version.

**Closed by titanous** 2017-01-03 16:34 UTC
