### ISSUE TITLE
Randomly occurring long delay during deployment

### ISSUE THREAD

**Issue by brad-werth** [flynn/flynn#4171] opened 2017-07-10 21:11 UTC
We are currently seeing a randomly occurring delay during deployment. This delay, when it occurs, is quite significant - often taking 10-50 minutes longer than normal to deploy. One we even got a `Job failed: execution took longer than 1h0m0s seconds` message. The delay seems to happen randomly and is not visibly tied to any external factors (server load, number of concurrent deployments, application complexity, etc.) in any obvious way. I would estimate that the delay is present in approximately 10-20% of our deploys. Sometimes an application will deploy several times in a row with no issues, other times the same application will have one slow deploy. Looking at memory usage and process lists did not yield any obvious insights, either. We initially increased our  SLUGBUILDER_DEFAULT_MEMORY_LIMIT on gitreceive to 2GB, in an unsuccessful attempt to alleviate the issue. We just further increased the SLUGBUILDER_DEFAULT_MEMORY_LIMIT on gitreceive to 3GB, just in case it was still set to too low of a value. 

The delay occurs after the output of `remote: -----> Compiled slug size is 61.35 MiB`. The output of `remote: -----> Creating release...` is then eventually output after a significant delay. Subsequent steps in the deploy process seem to take place normally, after the delay. 

If this sounds familiar to anyone from IRC, you may be recalling a conversation with my co-worker @bbaptist. It was speculated that this may have been related to having a lot of crashed jobs listed in `flynn host ps -a`, but this has recently happened on a machine without a lot of crashed jobs listed in `flynn host ps -a`, so this may have been somewhat of a red herring.

If there is any additional information I can provide to assist in the resolution of this matter, please do not hesitate to ask.

**Comment by titanous** [comment] 2017-07-11 15:47
What blobstore backend are you using? Have you examined the process list during one of these delays to determine if there are any processes consuming a lot of CPU, blocked on disk, memory, etc?

**Comment by bbaptist** [comment] 2017-07-11 16:07
S3 blobstore backend.

Checked the processes on the host running the deploy, little to no CPU usage, no memory pressure at all, did not check network or disk activity. I will do that the next time this happens.

**Comment by titanous** [comment] 2017-07-11 16:10
Please also grab the log lines for the `POST` requests to the blobstore, from `flynn -a blobstore log`, the initial lines will have `method=POST` and the subsequent ones will have the same request ID and the request duration.

**Comment by bbaptist** [comment] 2017-07-13 19:44
Some feedback on another stuck deploy.

`flynn-host` was the only think taking any CPU usage on the host running this deploy. It was spiking pretty high on and off. Overall load on the host was never above 0.10.

Over half the memory was always free on the host. 

Disk load measured by iotop was never more than a few hundred K/s.

Here are a few seconds of the blobstore log during a stuck run: https://gist.github.com/bbaptist/2eca6c48c3d7cff18d2ff5311dbf0ccb

**Comment by titanous** [comment] 2017-07-13 19:46
> Here are a few seconds of the blobstore log during a stuck run: 

If the issue is in the blobstore, I'll need to see the log for the entire duration of the deploy (you can omit the status endpoint requests, they are just noise).

**Comment by bbaptist** [comment] 2017-07-13 20:06
Right, here is the complete log from the time frame of the stuck deploy: https://gist.github.com/bbaptist/fd429856f6ecbbc51bede4d8fa6ef392

**Comment by bbaptist** [comment] 2017-07-13 20:12
Seems suspicious at https://gist.github.com/bbaptist/fd429856f6ecbbc51bede4d8fa6ef392#file-gistfile1-txt-L246

**Comment by titanous** [comment] 2017-07-13 20:13
Yep, that's what I was looking for. The likely explanation is that the S3 upload took a long time for some reason.

**Comment by bbaptist** [comment] 2017-07-13 20:16
Hmmm, have you heard reports that any of the other backends are more reliable?

**Comment by titanous** [comment] 2017-07-13 20:33
I haven't seen this before, the issue is probably specific to your environment. Other backends may or may not work better depending on a variety of environmental factors.

**Comment by bbaptist** [comment] 2017-07-13 21:23
Seems unlikely to be a bug in Flynn, so closing.

**Closed** 2017-07-13 21:51 UTC
