### ISSUE TITLE
Add path-based routing to the router.

### ISSUE THREAD

**Issue by enzolamzo** [flynn/flynn#2102] opened 2015-11-07 19:06 UTC
I'd like to be able to use one subdomain and route my apps on the sub-folder level.
Like www.myapp.com/api
www.myapp.com/app
It'll be really helpful in cases where the end user doesn't want to deal with cors issues.

**Comment by kevinob11** [comment] 2015-11-19 06:22
+1 don't want to deal with cors issues :)

**Comment by kevinob11** [comment] 2015-11-19 06:24
This is a likely a duplicate of #2069

**Comment by kwando** [comment] 2015-11-19 10:56
One workaround atm is to setup nginx as a reverse proxy in front of your cluster.
In theory you can even run a container with nginx that proxies to the other apps internally (via the discoverd DNS records).

(not sure how nginx does upstream dns resolving though, you might need the commercial license if you want runtime resolving of upstream servers).

Another is to build your own gateway app that just forwards requests.

**Comment by josephglanville** [comment] 2015-11-19 11:11
HAProxy can do dynamic backend resolution of 1.6: http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/

**Comment by kwando** [comment] 2015-11-19 12:16
@josephglanville cool, HAProxy is probably a fancier better load balancer/proxy than nginx, never used it though. For simple setups I think nginx is easier to configure though.

**Comment by philiplb** [comment] 2015-12-03 15:21
Just to note this here: If you put a reverse proxy upfront like, you have again a single point of failure unless you make the proxy redundant. Another piece of infrastructure to maintain where flynn would come to the rescue. :)

**Closed** 2015-12-12 17:50 UTC
Labels: enhancement, router
