### ISSUE TITLE
MySQL resource frequently and intermittently becomes unavailable

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#3199] opened 2016-07-28 19:01 UTC
Across multiple Python apps, I'm seeing sporadic errors connecting to MySQL. Attempting to reconnect works after a couple tries, but seems flaky.

```
2016-07-28T18:14:24.428539Z app[web.flynn1.xxxxx-8775e1fc-9405-4da2-9bff-3be5d0732fe1]: OperationalError: (2006, 'MySQL server has gone away')
2016-07-28T18:24:57.603792Z app[web.flynn1.xxxxx-8775e1fc-9405-4da2-9bff-3be5d0732fe1]: ERROR:root:Error connecting to MySQL on leader.mariadb.discoverd
```

All of them are using the discoveryd internal routes. Haven't given the external routes a shot yet to see if they're any more stable.

**Comment by titanous** [comment] 2016-07-28 19:05
Please collect the debug info from a host with `sudo flynn-host collect-debug-info`.

**Comment by michaelyork** [comment] 2016-07-28 19:07
Just emailed to logs@.

**Comment by titanous** [comment] 2016-07-28 19:36
I see a bunch of entries in the log for the MariaDB leader at `35c9ca70-c9e5-4ff5-90fd-7d5c285c2ee0`:

```text
2016-07-28 17:47:02 139936440789760 [Warning] Aborted connection 637 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.51.0' (Got an error reading communication packets)
2016-07-28 17:47:33 139936456710912 [Warning] Aborted connection 638 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.5.46' (Got an error reading communication packets)
2016-07-28 17:52:07 139936497339136 [Warning] Aborted connection 639 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got an error reading communication packets)
2016-07-28 17:55:22 139936441092864 [Warning] Aborted connection 640 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got an error reading communication packets)
2016-07-28 17:56:41 139936457014016 [Warning] Aborted connection 641 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.51.0' (Got an error reading communication packets)
2016-07-28 17:59:23 139936497036032 [Warning] Aborted connection 642 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.5.46' (Got an error reading communication packets)
2016-07-28 17:59:29 139936457317120 [Warning] Aborted connection 643 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got an error reading communication packets)
2016-07-28 17:59:41 139936440789760 [Warning] Aborted connection 644 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.51.0' (Got an error reading communication packets)
2016-07-28 18:09:06 139936456407808 [Warning] Aborted connection 622 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:09:16 139936440183552 [Warning] Aborted connection 624 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:09:28 139936440486656 [Warning] Aborted connection 621 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:24:27 139936456710912 [Warning] Aborted connection 645 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:35:00 139936441092864 [Warning] Aborted connection 647 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:42:14 139936457014016 [Warning] Aborted connection 648 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
2016-07-28 18:42:23 139936497339136 [Warning] Aborted connection 646 to db: 'b6579afc50c6909fd72a2697837a0905' user: '74c2674022907a0122d3ff5ecd2c4b65' host: '100.100.14.0' (Got timeout reading communication packets)
```

Is it possible for you to run tcpdump against `flynnbr0` on `flynn2` for traffic to `100.100.5.40` (the MariaDB leader)` and provide me with a pcap after several of these errors are logged?

**Comment by michaelyork** [comment] 2016-07-28 20:15
Happy to. Can you walk me through in a bit more detail? Can hop on IRC too.

**Comment by titanous** [comment] 2016-07-28 20:15
Sure, ping me in IRC.

**Comment by titanous** [comment] 2016-07-28 22:24
After a round of debugging, we found that this is caused by the default global [`wait_timeout`](https://mariadb.com/kb/en/mariadb/server-system-variables/#wait_timeout) value which appears to be set to `600`, instead of the default of `2880`. I think this is still an app bug, just made more apparently by the very low idle timeout.

@josephglanville Any idea where/why that `600` value is coming from and what we should do about it?

**Comment by josephglanville** [comment] 2016-07-29 01:41
The value for `wait_timeout` is the default for the MariaDB packages we use. The `MySQL has gone away` errors are expected if idle connections are being pooled. We could raise the timeout to avoid this but the errors themselves are not a problem as the connections will be re-established.

If it's causing a problem for the application there is definitely an error with the connection pool in use or the reconnection logic if none is being used.

**Comment by titanous** [comment] 2016-07-29 01:54
Okay, I'm going to close this. The default seems reasonable, and it is an application error so the lower timeout should make it more obvious.

**Closed by titanous** 2016-07-29 01:54 UTC
Labels: mariadb

**Comment by michaelyork** [comment] 2016-07-29 02:03
@titanous Thanks again for the help this afternoon. Agreed, this is on the app.
