### ISSUE TITLE
Container assigned invalid IP

### ISSUE THREAD

**Issue by ohhatiya** [flynn/flynn#2737] opened 2016-04-25 16:30 UTC
The controller service stopped responding to requests. Looking at logs for controller, it seemed like it was failing to heartbeat with discoverd. Here are links to debug info from the three nodes of the cluster:

https://gist.github.com/95a0fb7e06e98e7a8de6a4988955fea4
https://gist.github.com/5c3b014cc39d509e85ea5c2b41b8bfa3
https://gist.github.com/a89ab4cbe819d45b52de7f7ed45c2fca

**Comment by titanous** [comment] 2016-04-25 16:34
It looks like the postgres cluster is in a broken state after a discoverd interruption, please create a [gist](https://gist.github.com) with the output of `flynn-host log ip101005340-98a63631-9ced-4f15-b5f6-a8c277792cd8`

**Comment by titanous** [comment] 2016-04-25 16:39
Actually, that's not necessary, I have what looks like a bug in IP address assignment, I'm tracking down the root cause.

**Comment by titanous** [comment] 2016-04-27 16:04
It looks like one of the Postgres instances was assigned the invalid IP `100.100.6` instead of `100.100.6.2`. I have been unable to determine how/why this happened, but I opened #2749 to add more logging around that code path so that we can try to figure it out if it happens again. I've never seen this specific failure before, so it's likely very rare.

**Comment by titanous** [comment] 2016-07-10 02:56
Closing, this hasn't reoccurred and the code that handles setting up the network device is being replaced by #3030.

**Closed by titanous** 2016-07-10 02:56 UTC
Labels: bug
