### ISSUE TITLE
Migration to 16.04 causes failures on several applications

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3692] opened 2016-11-16 02:06 UTC
After some wrangling, I was able to make a new cluster stand up without axing its overtaxed bootstrapping node. However, the resulting cluster has numerous errors on several user applications.

I suspect the issue lies somewhere in the code migrating things to OverlayFS. I can reliably reproduce this issue, so I'm mostly leaving this ticket as a place to add further notes when I do so tomorrow. Is there anything (aside from debug info) that would be helpful for me to collect when I do?

**Comment by lmars** [comment] 2016-11-16 02:07
Let's start with the debug info and then take it from there.

**Comment by temujin9** [comment] 2016-11-16 21:07
User applications (which worked correctly prior to migration) fail with errors such as:

```
2016-11-16T20:41:26.374209Z app[app.ip10110246197-815ff722-9aef-4a32-81cf-5271788e3597]: + cron -f
2016-11-16T21:00:01.395767Z app[app.ip10110246197-815ff722-9aef-4a32-81cf-5271788e3597]: 
2016-11-16T21:00:01.395872Z app[app.ip10110246197-815ff722-9aef-4a32-81cf-5271788e3597]: System error
```

and

```
2016-11-16T21:06:19.879316Z app[web.ip10110246197-dfb560da-557b-4197-9009-99dec8a9a51e]: /usr/lib/ruby/1.9.1/psych.rb:297:in `initialize': No such file or directory - .release (Errno::ENOENT)
2016-11-16T21:06:19.879948Z app[web.ip10110246197-dfb560da-557b-4197-9009-99dec8a9a51e]:        from /usr/lib/ruby/1.9.1/psych.rb:297:in `open'
2016-11-16T21:06:19.880135Z app[web.ip10110246197-dfb560da-557b-4197-9009-99dec8a9a51e]:        from /usr/lib/ruby/1.9.1/psych.rb:297:in `load_file'
2016-11-16T21:06:19.880314Z app[web.ip10110246197-dfb560da-557b-4197-9009-99dec8a9a51e]:        from -e:1:in `<main>'
```

https://bazaarvoice.box.com/s/k8dso29w82jofj0e0bpdzsu8min5k9o1 has the debug-info.

**Comment by titanous** [comment] 2016-11-16 21:20
Is the second app looking for a file that starts with a dot? Are there any other apps failing, or is it only these two?

**Comment by titanous** [comment] 2016-11-16 21:21
Sorry, I meant the first app, the second one definitely is.

**Comment by josephglanville** [comment] 2016-11-16 21:24
The first app looks suspiciously like a PAM authentication error. I wonder if cron is doing something weird.

**Comment by temujin9** [comment] 2016-11-16 21:54
@titanous I do not do anything with relative paths in the first application.

This is also happening on other apps; a whole bunch of Ruby apps with essentially the same problem . . . in fact, a number of apps I'm pretty sure aren't ruby are having this problem in their logs . . . maybe an image is getting slotted wrong? Investigating further . . .

**Comment by temujin9** [comment] 2016-11-16 21:55
Yep, something's definitely rotten in Denmark. I've got a NodeJS application complaining about Ruby.

**Comment by titanous** [comment] 2016-11-16 21:55
The error is coming from this line: https://github.com/flynn/flynn/blob/48adeff42c4fb98822d51fd00eaf4f0c3adeef1d/slugrunner/runner/init#L34

@lmars might have some ideas as to why.

**Comment by lmars** [comment] 2016-11-17 01:27
@temujin9 the issue with apps deployed with `git push` was because their slugs were not being converted on restore, and after investigation it seems the artifacts did not have `blobstore=true` set in their metadata. I'm not sure why that was the case, but I have relaxed the check for slugs which need converting in #3701.

As for the cron `System error`, I can reproduce with a trivial crontab and running `cron -f` in Flynn. Watching the process with `strace` reveals that cron is getting a PAM related netlink response that it doesn't like:

```
[pid 102566] socket(PF_NETLINK, SOCK_RAW, 9) = 10
[pid 102566] fcntl(10, F_SETFD, FD_CLOEXEC) = 0
[pid 102566] sendto(10, "p\0\0\0M\4\5\0\1\0\0\0\0\0\0\0op=PAM:accountin"..., 112, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 112
[pid 102566] poll([{fd=10, events=POLLIN}], 1, 500) = 1 ([{fd=10, revents=POLLIN}])
[pid 102566] recvfrom(10, "\204\0\0\0\2\0\0\0\1\0\0\0 \0\0\0\377\377\377\377p\0\0\0M\4\5\0\1\0\0\0"..., 8988, MSG_PEEK|MSG_DONTWAIT, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 132
[pid 102566] recvfrom(10, "\204\0\0\0\2\0\0\0\1\0\0\0 \0\0\0\377\377\377\377p\0\0\0M\4\5\0\1\0\0\0"..., 8988, MSG_DONTWAIT, {sa_family=AF_NETLINK, pid=0, groups=00000000}, [12]) = 132
[pid 102566] getuid()                   = 0
[pid 102566] getuid()                   = 0
[pid 102566] close(10)                  = 0
[pid 102566] write(2, "\nSystem error\n", 14) = 14
```

It is likely the container is missing a capability that it needs, but given there are many other cron like solutions which don't interact so much with the system, I would suggest using one of those instead (e.g [Clockwork](https://github.com/Rykian/clockwork) / [Hcron](https://expl.info/display/HCRON/Home) / `while true; cmd; sleep 60; done`).

**Comment by temujin9** [comment] 2016-11-17 02:30
That container works fine and runs our backups flawlessly on 14.04.

**Comment by lmars** [comment] 2016-11-17 14:14
@temujin9 it is the upgrade of the kernel which has caused this to now be an issue.

To clarify what is going on, cron tries to call some PAM functions before executing the task. This worked with kernel 3.13 due to a bug which was subsequently fixed in 3.14 (see [here](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=543bc6a1a987672b79d6ebe8e2ab10471d8f1047)), so now with kernel 4.4.0 cron is failing because we don't enable `CAP_AUDIT_WRITE` for containers.

Given your use case is pretty simple (i.e. just running a single command every hour), I would consider just using a bash script:

```bash
while true; do
  /run-backup &
  sleep 3600
done
```

In future we plan to support scheduled tasks natively in Flynn.

**Comment by temujin9** [comment] 2016-11-17 17:03
I'm not fond of the sleep loop approach for several reasons, which is why I went the more complicated route. Is there a reason you don't enable CAP_AUDIT_WRITE?

How soon to you anticipate scheduled tasks?

**Comment by temujin9** [comment] 2016-11-17 17:05
It looks like the other fix is awaiting v20161117.0 - I will try that and report back, once it's dropped.

**Comment by titanous** [comment] 2016-11-17 17:12
`CAP_AUDIT_WRITE` is disabled as it is additional kernel surface area that is not useful for applications and is disabled for security reasons. Currently no ETA on scheduled tasks.

**Comment by temujin9** [comment] 2016-11-17 17:16
:-/ Okay, I will see if hcron/anacron/etc works as a replacement.

**Comment by lmars** [comment] 2016-11-17 20:34
@temujin9 can you elaborate on your reservations about the sleep loop? Just curious really.

**Comment by titanous** [comment] 2016-11-18 14:45
The fix in #3701 just landed via v20161118.0.

**Closed** 2016-11-28 18:29 UTC

**Comment by temujin9** [comment] 2017-01-10 21:27
@lmars We need more scheduling flexibility; given that this (aws cli, nothing y'all did) has in the past caused production outages, having the ability to restrict its operation to daylight hours reduced support concerns considerably.

Just doing a sleep loop does have the strong advantage of simplicity. Since the support concerns have been mostly put to bed, I'll go that way first.

**Comment by lmars** [comment] 2017-01-12 01:13
@temujin9 the bottom line here is that you should be able to run whatever you want in Flynn.

Once we have the Flynnfile you will be able to specify a custom list of Linux capabilities (it is already a field on `Release.ProcessType`, see [here](https://github.com/flynn/flynn/blob/master/controller/types/types.go#L109)).

**Comment by temujin9** [comment] 2017-01-12 01:16
@lmars I like that bottom line. Thanks.
