### ISSUE TITLE
Auto backup entire cluster to S3

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#3980] opened 2017-03-09 14:00 UTC
The option to create a backup of the entire cluster is awesome! 
It would be even more epic to have a service build into Flynn that could push a backup to S3 every day (or maybe even every hour) . 

We have had problems with Flynn, as we run it in production, this kind of thing would be epic!

**Comment by philiplb** [comment] 2017-03-09 14:08
We do exactly that via a Jenkins job having the Flynn CLI installed:

```bash
rm *.flynn-backup.tar || true
DAY=$(date -d "$D" '+%d')
HOUR=$(date +"%H")
flynn cluster backup --file "$DAY.$HOUR.flynn-backup.tar"
/home/jenkins/s3cmd/s3cmd --access_key=... --secret_key=... --region=... put "$DAY.$HOUR.flynn-backup.tar" s3://flynnbackup
```

This way, we have up to hourly (currently set to every three hours) backups of the last ~30 days. Older ones get simply overwritten.

**Comment by heldopslippers** [comment] 2017-03-09 14:13
Oeh Awesome! 
Thanxs so much! :)

**Comment by titanous** [comment] 2017-03-09 15:52
This is a duplicate of #1244.

**Closed by titanous** 2017-03-09 15:52 UTC
