### ISSUE TITLE
Status Page on the Dashboard not working due to an HTTP 401

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2988] opened 2016-06-25 10:53 UTC
Hi,
I just upgraded to the new stable version v20160624.1 and the status page of the dashboard refuses to work due to an HTTP 401 to the status endpoint. Have a look:
<img width="1039" alt="screen shot 2016-06-25 at 12 51 53" src="https://cloud.githubusercontent.com/assets/1672238/16356322/d1fd3186-3ad3-11e6-9a9c-d365f9626e40.png">

**Comment by jvatic** [comment] 2016-06-25 13:22
@philiplb what upgrade path did you take?

Check if `flynn -a dashboard env get STATUS_AUTH` is set, then try `flynn -a dashboard env set STATUS_KEY=$(flynn -a status env get AUTH_KEY)`.

**Comment by philiplb** [comment] 2016-06-25 13:33
Restore from backup. Will do. :-)

**Comment by philiplb** [comment] 2016-06-25 14:58
That did the trick. The restore from backup procedure could be a bit extended here to do this step if not done yet? :)

**Comment by titanous** [comment] 2016-06-25 18:11
Yeah, this should be fixed in the backup restore.

**Comment by jvatic** [comment] 2016-07-06 19:44
I'm unable to reproduce this using a backup from df75debfff62e378248c041c2fc86513fd38686f on the current master (29b2cd97c54a5969ce98287041fbb7418a126d0d).

**Comment by jvatic** [comment] 2016-07-28 17:35
It appears this is still an issue in some situations.

**Closed** 2016-09-15 19:37 UTC
Labels: kind/bug
