### ISSUE TITLE
"git push" returns "fatal: The remote end hung up unexpectedly"

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2979] opened 2016-06-23 00:44 UTC
https://bazaarvoice.box.com/s/r9j3n83yxobr8zcrm9cxsuyzw92ljp1f is the debug-info. System otherwise reported healthy. Issue persisted across backup and restore of cluster. Migration of all apps to a blank cluster worked around it.

**Comment by josephglanville** [comment] 2016-06-23 11:49
By the looks of it the slugbuilder job was failing with this error:
```
Error: Status 403 trying to pull repository flynn/slugbuilder: "<html>\n<head><title>403 Forbidden</title></head>\n<body>\n<h1>403 Forbidden</h1>\n<ul>\n<li>Code: AccessDenied</li>\n<li>Message: Access Denied</li>\n<li>RequestId: C1D613A0D45299A4</li>\n<li>HostId: 8QklbjHZMGsVhxYFwPQb7IvHlY+wz0nU7U9lkpA1ueYMyzg8vkjCQLf5pbPN/1P1z+jD571XjWI=</li>\n</ul>\n<hr/>\n</body>\n</html>\n"
```

An unfortunate oversight in recent debug log collection changes is that we aren't collecting slugbuilder output as it's not marked as a system app. (though this is probably correct as it could contain private information I guess)

So it's not clear if there was further issues but this definitely looks like an S3 bucket permissions issue or similar.

**Comment by titanous** [comment] 2016-06-23 14:03
That error is from flynn-host, and is caused by an incorrect `SLUGBUILDER_IMAGE_URI` env var. I'll add some logging to make it more clear what the exact value of the variable is.

**Comment by titanous** [comment] 2016-06-23 16:00
After a closer look, this appears to have been due to a lack of a rewrite of that variable during the backup restore. I'm looking at the code to sort out how it happened.

**Comment by titanous** [comment] 2016-07-05 22:18
I was unable to determine the cause of this, but I suspect it was a mismatch in the TUF repo that would have been fixed in a subsequent release. Please open a new issue if you see it again.

**Closed by titanous** 2016-07-05 22:18 UTC
