### ISSUE TITLE
SchedulerSuite.TestScaleTags failure

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2550] opened 2016-03-09 21:59 UTC
```text
21:18:20.386 FAIL: test_scheduler.go:78: SchedulerSuite.TestScaleTags

++ 21:18:03.336 created app falcons-denounce-sudbury (0cbf32ce-948e-47f1-a3dc-f674612b3022)
++ 21:18:03.446 setting host tags: 0282f627 => map[active:true]
++ 21:18:03.453 scaling printer=2
++ 21:18:10.672 setting host tags: 877300de => map[active:true]
++ 21:18:10.677 scaling printer=4
test_scheduler.go:168:
    // check jobs distributed across hosts 1 and 2
    assertHostJobCounts(map[string]int{host1.ID(): 2, host2.ID(): 2})
test_scheduler.go:151:
    t.Assert(actual, c.DeepEquals, expected)
... obtained map[string]int = map[string]int{"0282f627":4}
... expected map[string]int = map[string]int{"0282f627":2, "877300de":2}
```

https://ci.flynn.io/builds/20160309205910-385a550a

**Comment by lmars** [comment] 2016-03-10 04:05
Duplicate of #2381.

**Closed by lmars** 2016-03-10 04:05 UTC
Labels: bug, ci-flake
