### ISSUE TITLE
Inconsistent results when trying to deploy a Python app

### ISSUE THREAD

**Issue by jperals** [flynn/flynn#3650] opened 2016-11-09 09:56 UTC
In order to let Flynn deploy my app I had to add a `runtime.txt` with this content:

```
python-2.7.11
```

Then it was working, Python 2.7.11 was being fetched and installed and then also the packages in my `requirements.txt`, and so on.

But then I had some issues because I added a `package.json` and my app stopped being detected as Python, so I added a `Procfile` as well, but this led to other problems, so in the end I rolled everything back with Git... I don't know how this issues can be related, but I can't find any explanation on why now, with exactly the same content as before (`python-2.7.11`) in the `runtime.txt`, the deployment is failing with this output:

```
(...)
-----> Installing python-2.7.11
       !     Requested runtime (python-2.7.11) is not available for this stack (cedar-14).
       !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote: ERROR: Build failed: exec: job exited with status 1
(...)
```
I have also tried `python-2.7.5`, `python-2.7.12` and without `runtime.txt`.

**Comment by josephglanville** [comment] 2016-11-09 10:09
Flynn's buildpack support uses the Heroku buildpacks, which for Python only support a single Python 2 and Python 3 runtime at a time. You can check which runtimes are currently supported here: https://devcenter.heroku.com/articles/python-support

So in order to build a new slug for your app you will need to switch to `python-2.7.12`.
The supported runtimes are periodically updated by Heroku and Flynn ships the latest buildpacks with each stable release.

**Comment by jperals** [comment] 2016-11-09 10:24
As I said, I already tried `python-2.7.12`. Now I just tried it again with the same result:

```
(...)
-----> Installing python-2.7.12
       !     Requested runtime (python-2.7.12) is not available for this stack (cedar-14).
       !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
(...)
```

**Comment by josephglanville** [comment] 2016-11-09 10:28
Can you paste the full build logs, that except is not enough to determine what else could be wrong.

**Comment by jperals** [comment] 2016-11-09 10:50
I just uploaded some gists here: https://gist.github.com/jperals/9f85d8e720d7c9832dcc1f886c908b01

Which correspond to (in this order):
- The output from one of yesterday's deployment attempts, which failed for other reasons but fetched Python successfully.
- The output from one of today's deployment attempts, which couldn't fetch Python.
- The output of `flynn log`, which only seems to reflect my earlier attempts to use a `package.json` and a `Procfile`+gunicorn. Now I'm not using any of those.

Is this useful or need something else? Thanks for your help!

**Comment by josephglanville** [comment] 2016-11-09 11:03
Try `flynn env set BUILDPACK_URL="https://github.com/heroku/heroku-buildpack-python"`.
This will cause Flynn to fetch the buildpack from Git instead of using the version installed in the slugbuilder which can eliminate a few classes of issues.

**Comment by jperals** [comment] 2016-11-09 13:10
Unfortunately this didn't help much, but provoked other errors.

After running `flynn env set BUILDPACK_URL="https://github.com/heroku/heroku-buildpack-python"` I got this:

```
$ git push flynn master
Counting objects: 294, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (215/215), done.
Writing objects: 100% (294/294), 219.52 KiB | 0 bytes/s, done.
Total 294 (delta 33), reused 0 (delta 0)
-----> Building myapp...
-----> Fetching custom buildpack
remote: ERROR: Build failed: exec: job exited with status 128
To https://git.demo.localflynn.com/myapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.demo.localflynn.com/myapp.git'
```

And after a while I tried again and got this:

```
$ git push flynn master
remote: Internal server error
fatal: unable to access 'https://git.demo.localflynn.com/myapp.git/': The requested URL returned error: 500
```

**Comment by josephglanville** [comment] 2016-11-09 13:32
Interesting. Could you post the debug information collected with `flynn-host collect-debug-info`. If it creates a tarball email to `logs@flynn.io`.

By the looks of it you are running Flynn locally, perhaps in Vagrant. The log indicates it wasn't able to fetch the custom build pack, and potentially this is also the root cause of not being able to fetch the runtime. Could you verify that the Vagrant VM has unfettered connectivity to the Internet?

**Comment by jperals** [comment] 2016-11-09 14:00
The `flynn-host collect-debug-info` command uploaded this gist itself: https://gist.github.com/anonymous/01e295bc16165cd58a7b5a69772c0f3d

Yes, I am using Flynn locally in Vagrant. And I noticed that `make ssh` didn't work either, until after I restarted the VM with `make down`, `make up` and `vaillant up` (the last one was possibly not necessary, I guess). And now also the deployment process is behaving again like yesterday (Python and the packages are being fetched).

So it seems like the VM can have connectivity problems if it's up for very long?

**Comment by josephglanville** [comment] 2016-11-09 14:04
I am not sure, I don't use Vagrant that much but if that is an issue it is a bug in the hypervisor most likely.

Did restarting the VM get you back into a state where you can deploy your application? You can likely unset the BUILDPACK_URL environment variable if you want, it will slow down slug building time if it has to fetch the buildpack every time if you have verified that connectivity was the source of the problems.

**Comment by jperals** [comment] 2016-11-09 14:22
> Did restarting the VM get you back into a state where you can deploy your application?
Yes! Well, to be exact, it fails later on "as expected" just like it did before :-) But not related to this issue.

If I go to the advanced network settings for the VM in Virtualbox and uncheck the "Cable Connected" option, then the problem comes back. So I would say you're right, this must have been the problem...

**Comment by josephglanville** [comment] 2016-11-09 14:24
Cool, closing this one as resolved. Thanks for using Flynn! 😀

**Closed by josephglanville** 2016-11-09 14:24 UTC
