### ISSUE TITLE
Is it time to mark Flynn as not safe for production?

### ISSUE THREAD

**Issue by kareemcoding** [flynn/flynn#4601] opened 2020-07-02 10:37 UTC
I've been following the dev work of Flynn and these issues for close to 6 months now and I think it's pretty safe to say that Flynn is no longer be actively maintained like it used to. I've not seen any new features for as long as I've been following and the last update on the **Security improvements** hasn't been touched since Aug 2019.

Should the website be taken down and instead just redirect to the repo? It's currently very misleading and paints the picture of a well maintained, stable and production ready platform.

**Comment by jadetr** [comment] 2020-07-07 00:41
I agree. I am looking for a PaaS, get excited by the Flynn promise and website, installed Flynn with the documentation on 3 servers, encountered few problems (finally get stuck with redis being too old, I need 4+). The more I search, the more I realise that Flynn seems unmaintained. I think adding some notes on the website AND git repo that this project is maintained part-time or unmaintained would greatly help to make better choice.

**Comment by questionaut** [comment] 2020-07-09 21:29
@jadetr According to this post https://stackoverflow.com/questions/62799550/how-to-route-multiple-certificates-to-one-flynn-application the project is not "abandoned"

**Comment by kareemcoding** [comment] 2020-07-16 13:47
The fact that this issue itself has not had an official response speaks volumes for the "production rediness" of Flynn as of today.

**Comment by jadetr** [comment] 2020-07-16 13:55
I finally install CapRover. It's not HighAvailability by design but it allows you to scale to several machines pretty easily.
https://caprover.com/
Have fun :)

**Comment by bayukp** [comment] 2020-07-17 16:36
I almost use this, but change my mind and switch to dokku. But @jadetr suggestion seems more promising since I want web UI very much

**Comment by chris-rutherfurd** [comment] 2020-08-03 13:12
Anyone got advice in an alternative to flynn, I have tried convox and caprover but found they where more aimed at orchestration whereas I am looking for something process orientated more like flynn and heroku, did look at dokku which looks interesting but would rather something with clustering to run on 3 servers.

I tried to use Flynn and get it working both on a 3 server cluster and a 5 server cluster on digital ocean but had a wide ranging number of issues including freezes when provisioning apps or databases using the dashboard as well as the cli, and lock ups meaning that just the action of pressing the save button in the Web ui to create an app results in an endless waiting spinner which doesn't lead to anything, trying to provision a myself database with a public route did the same thing. 

Flynn appears to be exactly what I need if only it was more stable and had a more recent stable release as the latest releases channel seems to have issues.

**Comment by rlangfordBV** [comment] 2020-10-29 15:39
My org is moving off.  I just nuked 3 Flynn clusters yesterday 💥

**Comment by fr3fou** [comment] 2020-10-29 15:51
> My org is moving off. I just nuked 3 Flynn clusters yesterday 💥

what are you moving to?

**Comment by sunnysingh** [comment] 2021-01-21 23:43
I'm planning to move away from Flynn as well. Mainly due to lack of updates and support (either official or community).

Definitely recommend CapRover or Dokku if you're looking for an alternative. I personally tried CapRover for a while (it worked well) until moving to Render.com because I didn't want to maintain my own server and also wanted other features that Render provides.

**Comment by JosXa** [comment] 2021-01-25 15:37
> I finally install CapRover. It's not HighAvailability by design but it allows you to scale to several machines pretty easily.
> [caprover.com](https://caprover.com/)
> Have fun :)

The difference is that CapRover is a pure (swarm) container orchestrator, while Flynn ~sees~ *saw itself as an extension of Dokku, a generic PaaS that can run any application via build packs but also _happens_ to support Dockerfiles and images.

**Comment by sunguroku** [comment] 2021-01-27 04:35
Just thought I'd drop in here - I am the maintainer of [Porter](https://github.com/porter-dev/porter), which can be a replacement for flynn. Porter is a PaaS that runs on top of Kubernetes so it supports things Kubernetes natively excels at like autoscaling. It has a nice web UI, CLI, supports all three major cloud providers (AWS, GCP, DO), integrates with private registries, and sets up https and custom domains.

It's a young project but we are working full time on it with funding from Y Combinator, and we're most definitely not going to pull a flynn and stop maintaining. We're determined to make Porter the new open source Heroku - I would appreciate if you could check it out and leave a star/watch the repo to follow our progress!

**Comment by JosXa** [comment] 2021-01-27 08:27
@sunguroku Awesome, thanks for dropping in! Just the right moment to spread the word, I'll try it out

**Comment by kareemcoding** [comment] 2021-01-27 14:58
Awesome work @sunguroku I'll check it out, but I have to agree with @JosXa DO is definitely not part of the big three 😂 

AWS, Azure, GCP is definitely the big three, Azure is excelling with Enterprises right now!

**Comment by JosXa** [comment] 2021-01-27 15:25
[ Insert "Can't go off-topic in a civilized way when there's no admin to enable GH Discussions" meme here ]

Yea, Azure functions in C# are crazy productive for example! I heard from an MS guy that their metrics show they're pretty much exactly half the size of AWS, while GCP has around half the adoption of Azure.

**Comment by sunguroku** [comment] 2021-01-27 15:37
That's true 😅  It's just that DO is quite popular among individual devs and early stage startups who tend to find PaaS's like Flynn and Porter more useful.

That said, Azure is def on our radar and we'll get to supporting it at some point!

**Comment by xXKynarethXx** [comment] 2021-01-27 16:03
@sunguroku nice to hear that! I also would find hetzner really useful, as its prices are very good! I know they are not that big, but they already support a bunch of stuff (terraform, cloud native LB, node driver, volumes, etc.)! I heard they also support open source development financially :)

**Comment by titanous** [comment] 2021-02-18 21:58
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

**Closed by titanous** 2021-02-18 21:58 UTC
