### ISSUE TITLE
Default AWS cluster disk full (after almost no usage)

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3163] opened 2016-07-21 12:48 UTC
I just used a AWS single node cluster (with the default 2x 50GB disks, `v20160624.1`) for some testing with around 5 applications, and now the disk appears to be full:

```
Cloning into '/tmp/app'...
-----> Building shipping-service...
-----> Gradle app detected
mkdir: cannot create directory '/tmp/jvm-common': No space left on device
ERROR: Build failed: exec: job exited with status 1
exit status 1
```

The apps result in slugs usually around 150MB (Java stuff)

On this host I see:

```
  System information as of Tue Jul 12 17:48:58 UTC 2016

  System load:  0.13               Users logged in:         0
  Usage of /:   46.2% of 49.08GB   IP address for eth0:     10.0.4.8
  Memory usage: 81%                IP address for docker0:  172.17.0.1
  Swap usage:   0%                 IP address for flynnbr0: 100.100.12.1
  Processes:    610
```
and
```
ubuntu@ip-10-x-x-x:~$ df -Th
Filesystem                                         Type      Size  Used Avail Use% Mounted on
udev                                               devtmpfs  2.0G   12K  2.0G   1% /dev
tmpfs                                              tmpfs     396M  560K  395M   1% /run
/dev/xvda1                                         ext4       50G   48G     0 100% /
none                                               tmpfs     4.0K     0  4.0K   0% /sys/fs/cgroup
none                                               tmpfs     5.0M     0  5.0M   0% /run/lock
none                                               tmpfs     2.0G   74M  1.9G   4% /run/shm
none                                               tmpfs     100M     0  100M   0% /run/user
flynn-default                                      zfs        27G     0   27G   0% /flynn-default
flynn-default/4a8d2f49-2470-4fec-9f07-a855c0da282e zfs        27G  128K   27G   1% /var/lib/flynn/volumes/zfs/mnt/4a8d2f49-2470-4fec-9f07-a855c0da282e
flynn-default/fcd43a04-2572-45a3-b946-44273a964eee zfs        49G   22G   27G  45% /var/lib/flynn/volumes/zfs/mnt/fcd43a04-2572-45a3-b946-44273a964eee
```

The debug log seems to be quite big as well:

```
INFO[07-21|12:42:17] uploading logs and debug information to a private, anonymous gist 
INFO[07-21|12:42:17] this may take a while depending on the size of your logs 
INFO[07-21|12:42:17] getting flynn-host logs 
INFO[07-21|12:42:17] getting job logs 
INFO[07-21|12:42:46] getting system information 
INFO[07-21|12:42:46] Total size of 257420877 bytes exceeds gist limit, falling back to tarball. 
```

What could cause this?  If you really need the 25MB tarball I can upload it somewhere.

**Edit:** Uploaded the debug logs
[debug.tar.gz](https://github.com/flynn/flynn/files/376107/debug.tar.gz)

**Comment by josephglanville** [comment] 2016-07-21 13:23
Hi @IsNull ideally if you could upload the debug info that is always useful. It contains a bunch of stuff that we would ask to collect to determine root causes for issues.

It looks like the root volume has filled up.
If you could use `du` to narrow down which directory is consuming the space that would be great.

**Comment by IsNull** [comment] 2016-07-21 14:07
Hi there,

Its not so easy because recursive scan commands tend to fail (out of disk :))

But I found out that the issue probably comming from `/var/lib/docker/aufs` specifically `mnt` and `diff` don't return/hang on `sudo du -sh`

**Comment by titanous** [comment] 2016-07-21 14:19
This sounds like #38, a bug which is fixed in the nightly. I'm going to do a stable release today that will contain the fix.

In the mean time, you can try running this script to clean things up: https://gist.github.com/lmars/6d072bc88c3a4c9f87d2

**Comment by IsNull** [comment] 2016-07-21 14:24
Ok the du process finally completed on aufs and got a impressive `229G	docker/aufs/`. 
I will try the script and report back.

>  I'm going to do a stable release today that will contain the fix.

Cool, I will trash the test cluster and install the new stable and then we see in a week or so if all is resolved. As long as I don't delete the cluster I'm happy to provide you with whatever information you need.

**Comment by IsNull** [comment] 2016-07-21 14:35
Ok I got the script to run without creating a actual file:
`bash <(curl -s https://gist.githubusercontent.com/lmars/6d072bc88c3a4c9f87d2/raw/49f0efbfcc5433fea9fded5e5c0baf39d1ad9c06/flynn-cleanup.sh)`

This gives me output like

```
[...]
rm: cannot remove '/var/lib/docker/aufs/mnt/tmp-ip10048-0d0f065c-65ba-474a-a706-27aadbf92095': Device or resource busy
rm: cannot remove '/var/lib/docker/aufs/mnt/tmp-ip10048-92c88cbd-5dcd-491f-a003-41fd90b590ec': Device or resource busy
```

Still running ...

**Comment by titanous** [comment] 2016-07-21 23:19
Since this issue is fixed in master and the cleanup script works as a stopgap, I'm going to close this issue.

**Closed by titanous** 2016-07-21 23:19 UTC

**Comment by brettneese** [comment] 2016-08-19 18:46
@titanous we are having this problem as well, but when we run the script, the ```leaked var``` is empty and we get "/dev/fd/63: no such file or directory" errors.

any thoughts? we are on v20160726.0 (haven't had a chance to upgrade yet) and have to tread lightly because this system is serving some production traffic (though we have a failover in place as well). but we can't launch any new images. 

running the first half of the 

```sudo find $mnt_dir -maxdepth 1 -name 'tmp-*' -printf '%f\n' | grep -v -f <(flynn-host ps -q | cut -d '-' -f 2-)```

command returns some things, as does the second half (before the pipe/after the pipe) but running them together returns nothing.


cc: @mnaughto

**Comment by titanous** [comment] 2016-08-19 19:30
@brettneese That script is no longer relevant, the leak in question was fixed when we switched to libcontainer.

What directories are consuming space?

**Comment by titanous** [comment] 2016-08-19 19:30
@brettneese Also, please open a new issue with the details.
