### ISSUE TITLE
Failed to stop jobs when flynn-host daemon is stopped.

### ISSUE THREAD

**Issue by monaka** [flynn/flynn#1660] opened 2015-07-13 05:29 UTC
When I stop flynn-host by executing ```# stop flynn-host``` on the node running on Ubuntu,
there have some errors /var/log/upstart/flynn-host.log like this:

```
ERRO[1119] Removing active id tmp-monaflynn1-08088cae5b3e453ab120db3377065e58 
now=2015-07-13T05:21:22+0000 fn=cleanup job.id=monaflynn1-08088cae5b3e453ab120db3377065e58 at=pinkerton status=error err="rename /var/lib/docker/aufs/mnt/tmp-monaflynn1-08088cae5b3e453ab120db3377065e58 /var/lib/docker/aufs/mnt/tmp-monaflynn1-08088cae5b3e453ab120db3377065e58-removing: device or resource busy" app=host backend=libvirt-lxc
now=2015-07-13T05:21:22+0000 job.id=monaflynn1-08088cae5b3e453ab120db3377065e58 at=finish app=host backend=libvirt-lxc fn=cleanup
now=2015-07-13T05:21:22+0000 app=host at=start backend=libvirt-lxc fn=cleanup job.id=monaflynn1-36f4d743d8584b04b1c6a03ee957e176
ERRO[1119] Removing active id tmp-monaflynn1-36f4d743d8584b04b1c6a03ee957e176 
now=2015-07-13T05:21:22+0000 job.id=monaflynn1-36f4d743d8584b04b1c6a03ee957e176 err="device or resource busy" at=pinkerton status=error app=host backend=libvirt-lxc fn=cleanup
now=2015-07-13T05:21:22+0000 app=host backend=libvirt-lxc fn=cleanup job.id=monaflynn1-36f4d743d8584b04b1c6a03ee957e176 at=finish
now=2015-07-13T05:21:22+0000 at=start backend=libvirt-lxc fn=cleanup job.id=monaflynn1-a875e3e4d8884103b4e67c936ed09ffa app=host
ERRO[1119] Removing active id tmp-monaflynn1-a875e3e4d8884103b4e67c936ed09ffa 
now=2015-07-13T05:21:22+0000 at=pinkerton status=error err="device or resource busy" job.id=monaflynn1-a875e3e4d8884103b4e67c936ed09ffa app=host backend=libvirt-lxc fn=cleanup
now=2015-07-13T05:21:22+0000 app=host backend=libvirt-lxc fn=cleanup job.id=monaflynn1-a875e3e4d8884103b4e67c936ed09ffa at=finish
now=2015-07-13T05:21:22+0000 fn=cleanup job.id=monaflynn1-6f1188e826d24c05aa76975d70b3abdd app=host backend=libvirt-lxc at=start
ERRO[1119] Removing active id tmp-monaflynn1-6f1188e826d24c05aa76975d70b3abdd 
now=2015-07-13T05:21:22+0000 app=host backend=libvirt-lxc fn=cleanup job.id=monaflynn1-6f1188e826d24c05aa76975d70b3abdd at=pinkerton status=error err="device or resource busy"
now=2015-07-13T05:21:22+0000 at=finish job.id=monaflynn1-6f1188e826d24c05aa76975d70b3abdd app=host backend=libvirt-lxc fn=cleanup
now=2015-07-13T05:21:22+0000 fn=cleanup job.id=monaflynn1-3a5041ae1b844c63a34219de475751f6 app=host backend=libvirt-lxc at=start
ERRO[1119] Removing active id tmp-monaflynn1-3a5041ae1b844c63a34219de475751f6 
now=2015-07-13T05:21:22+0000 app=host err="device or resource busy" at=pinkerton status=error backend=libvirt-lxc fn=cleanup job.id=monaflynn1-3a5041ae1b844c63a34219de475751f6
now=2015-07-13T05:21:22+0000 job.id=monaflynn1-3a5041ae1b844c63a34219de475751f6 app=host backend=libvirt-lxc at=finish fn=cleanup
```

And there are some containers still running.

```
 $ virsh -c lxc:/// list 
 Id    Name                           State
----------------------------------------------------
 3687  monaflynn1-e6c02989ffe543a8acc362591819b8f0 running
 4610  monaflynn1-5dfca1e4d04e4605b03c4526d2aafb6e running
 5849  monaflynn1-d1b105bff6254ec4b6ea5fd70060ccf8 running
```

Is this an expected behavior?

**Comment by titanous** [comment] 2015-07-13 14:30
The errors from the log that you posted are not the cause of the containers that are still running (they are #38, which is partially fixed in the latest release).

I'll need the full cluster debug info to understand what's going on here.

**Comment by monaka** [comment] 2015-07-13 21:23
I see. I'll try to reproduce it later.

**Comment by titanous** [comment] 2015-08-15 17:27
Closing until we get more info.

**Closed by titanous** 2015-08-15 17:27 UTC
