### ISSUE TITLE
Cluster in an undefined state

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2520] opened 2016-03-03 09:22 UTC
Hi,

this morning, the cluster went into a funky state. Also, the deployed application is down.
The status result:
```js
{
  "data": {
    "status": "unhealthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-worker": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "dashboard": {
        "status": "unhealthy"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "flannel": {
        "status": "unhealthy"
      },
      "gitreceive": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "postgres": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "router": {
        "status": "healthy",
        "version": "v20160218.0"
      }
    },
    "version": "v20160218.0"
  }
}
```

```bash
flynn-host ps
```

> 10:05:52.628333 host.go:140: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused

Collecting the gist gave me in between this:
> INFO[03-03|10:08:08] getting job logs
> EROR[03-03|10:08:38] error getting job logs, falling back to on-disk logs err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"

And the gist of the first node:
https://gist.github.com/a5b524f7d613cd00239e

BTW:
It contained a 0-debug-output.log, but that didn't want to gist due to "Error: "\xC2" on US-ASCII". So I ran it through tr:
```bash
cat 0-debug-output.log | tr -d '\200-\377' > 0-debug-output.clean.log
```

**Comment by philiplb** [comment] 2016-03-03 15:26
the fix command doesn't work as well:
```
sudo flynn-host fix --min-hosts 3
EROR[03-03|16:13:05] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
16:13:05.810540 host.go:140: error connecting to discoverd, use --peer-ips: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused
```

**Comment by titanous** [comment] 2016-03-03 15:27
The gist link you posted is a 404.

**Comment by philiplb** [comment] 2016-03-03 15:30
Whoops, sry, correct one:
https://gist.github.com/a5b524f7d613cd00239e

**Comment by titanous** [comment] 2016-03-03 16:33
@philiplb It looks like the discoverd consensus cluster stopped working, this can be due to network interruption or node failure. In addition, this failure triggered a bug that was fixed in the most recent nightly release that causes the containerinit processes for your apps to freeze up and stop heartbeating to discoverd permanently.

**Comment by philiplb** [comment] 2016-03-03 16:37
@titanous ok, thx. The nodes are all up and running. There might have been a network outage for a few seconds to minutes, hard to tell. I'll reboot all nodes.

**Comment by philiplb** [comment] 2016-03-03 16:46
@titanous nope, a blind reboot of all three nodes didn't work. The network between them is fine though.

**Comment by titanous** [comment] 2016-03-03 16:48
Please run `sudo flynn-host collect-debug-info` on all nodes and post the logs here so @josephglanville can investigate the resurrection failure.

I'd suggest starting a new cluster with the latest nightly so that you get the recent bugfixes. Let me know if you have data that you'd like to recover from Postgres on this cluster, we have some tools for that.

**Comment by philiplb** [comment] 2016-03-03 16:49
@titanous 
Ok, will do. I'll just wait for the next stable release. There was nothing important on that cluster.

**Comment by philiplb** [comment] 2016-03-03 16:54
@josephglanville 
First node: https://gist.github.com/4dae3a077592bc671f3a
Second node: https://gist.github.com/505c4cbd0cbb819ab24c
Third node: https://gist.github.com/46370760538b351a0da8

**Comment by philiplb** [comment] 2016-03-03 17:01
@titanous @josephglanville 
I will leave this defect cluster around for a bit (until tomorrow or the day after tomorrow) in case you want to have a direct look at it.

**Comment by josephglanville** [comment] 2016-03-03 17:54
Hmm, it looks like it never got to starting the cluster-monitor.
In fact all the machines seem to have gotten hung trying to restore from the state database.

There isn't a lot of logs here but I imagine this is related to the container-init RPC hanging issue that has been fixed on master.

**Comment by josephglanville** [comment] 2016-03-03 18:06
@philiplb if we could sort out SSH access that would be ideal. I need to get a goroutine stack trace to determine why the flynn-host processes are hanging. My key is available on Github at https://github.com/josephglanville.keys.
If you could email me access details to joseph@flynn.io that would be awesome.

**Comment by philiplb** [comment] 2016-03-04 07:38
@josephglanville I've sent you an email. :)

**Comment by josephglanville** [comment] 2016-03-04 08:54
Ok, I logged into the first node in your cluster and sent flynn-host a SIGQUIT to dump a go-routine stack trace:
```
SIGQUIT: quit
PC=0x488fb1

goroutine 6 [syscall, 973 minutes]:
runtime.notetsleepg(0x11006a0, 0xffffffffffffffff, 0xb76901)
	/usr/local/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208016f68 sp=0xc208016f40
runtime.signal_recv(0x172)
	/usr/local/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc208016fa0 sp=0xc208016f68
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc208016fe0 sp=0xc208016fa0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208016fe8 sp=0xc208016fe0
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 1 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.func·038(0xc208180700, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:101 +0x3ca
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).View(0xc208046820, 0xc2082774a8, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:583 +0xe7
main.(*State).Restore(0xc20824e8c0, 0x7fe73af28b48, 0xc20806d000, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:114 +0x210
main.runDaemon(0xc20800ad80)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/host.go:369 +0x4b1d
github.com/flynn/flynn/host/cli.Run(0x7fffa456cf29, 0x6, 0xc2080b7760, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/cli/cli.go:59 +0x4a8
main.main()
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/host.go:132 +0x8c1

goroutine 17 [syscall, 973 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive, 973 minutes]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208064b70)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 47 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2080cf7d0, 0x2b, 0x7fe73af1ca40, 0xc208334e30)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b540, 0xc208049a40, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 48 [semacquire, 973 minutes]:
sync.(*RWMutex).Lock(0xc208046978)
	/usr/local/go/src/sync/rwmutex.go:87 +0xa4
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).mmap(0xc208046820, 0x40000, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:215 +0x5e
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).allocate(0xc208046820, 0x1, 0x6f7331, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:652 +0x158
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*Tx).allocate(0xc208200e00, 0x1, 0x7fe726b86000, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:412 +0x48
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*Tx).Commit(0xc208200e00, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:174 +0x36b
github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).Update(0xc208046820, 0xc208275c90, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:559 +0x169
main.(*State).persist(0xc20824e8c0, 0xc20825adb0, 0x2b)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:273 +0x69
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20825adb0, 0x2b, 0x7fe73af1ca40, 0xc208379940)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:425 +0x280
main.(*libvirtContainer).watch(0xc20820b180, 0xc208049b60, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 50 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20825b710, 0x2b, 0x7fe73af1ca40, 0xc2083b82e0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b360, 0xc208049f20, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 51 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20825a120, 0x2b, 0x7fe73af1ca40, 0xc2083b8440)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820af50, 0xc208258000, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 52 [semacquire, 973 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20825aba0, 0x2b, 0x7fe73af1ca40, 0xc20838a200)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b090, 0xc2082580c0, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 53 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20825b260, 0x2b, 0x7fe73af1ca40, 0xc2083b8180)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b270, 0xc208258180, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 54 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2081c4e40, 0x2b, 0x7fe73af1ca40, 0xc2083b85a0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b810, 0xc208258240, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 55 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2080e9dd0, 0x2b, 0x7fe73af1ca40, 0xc2083b8700)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b900, 0xc208258300, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 56 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2082877d0, 0x2b, 0x7fe73af1ca40, 0xc2083484b0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b630, 0xc2082583c0, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 57 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc20821e0c0, 0x2b, 0x7fe73af1ca40, 0xc208348490)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b720, 0xc208258480, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 58 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2080ce540, 0x2b, 0x7fe73af1ca40, 0xc20835a8b0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820b9f0, 0xc208258540, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

goroutine 59 [semacquire, 970 minutes]:
sync.(*Mutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc20824e8d8)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
main.(*State).SetStatusFailed(0xc20824e8c0, 0xc2080cec00, 0x2b, 0x7fe73af1ca40, 0xc20835a750)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/state.go:412 +0x43
main.(*libvirtContainer).watch(0xc20820bae0, 0xc208258660, 0x0, 0x0, 0x0)
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:742 +0xe56
created by main.(*LibvirtLXCBackend).UnmarshalState
	/tmp/tmp.lQE0LWFbN0/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:1177 +0x806

rax     0xca
rbx     0x11006a0
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x11006a0
rsi     0x0
rbp     0x1
rsp     0xc208016ec0
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x0
r13     0x3
r14     0x588
r15     0x10
rip     0x488fb1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
```

**Comment by josephglanville** [comment] 2016-03-04 08:56
@titanous looks like we have some sort of deadlock on state restore, it looks like it may be the same as #2481

**Comment by josephglanville** [comment] 2016-03-04 09:36
Ok so the deadlock happens between `Restore` and `SetStatusFailed` and was made worse by the changes I made to support persistent slots (though technically it existed prior to this but only on unclean shutdown when the resurrection bucket was nil). Unfortunately I don't know what actually triggers the underlying problem as it doesn't happen in my testing usually but can be reliably triggered with @philiplbs cluster.

I tried changing the lock used to traverse the jobs bucket in `Restore` to an `RLock` but that didn't help. Doing the traversal without holding the lock unblocks the deadlock.

**Comment by philiplb** [comment] 2016-03-04 09:43
@josephglanville 
Feel free to play arround with the cluster as you want (like installing debug-versions of Flynn etc.). There is really nothing important on it, just a playground.

**Comment by josephglanville** [comment] 2016-03-04 10:08
@philiplb thanks for allowing me to debug the issue on your cluster, it was difficult to reproduce ourselves. With your help I was able to fix the underlying bug. :)

**Comment by philiplb** [comment] 2016-03-04 10:16
@josephglanville glad that it helped. :)
Curious: When will the fix be deployed in a stable version?

**Comment by josephglanville** [comment] 2016-03-04 10:28
Probably in the next few days. For now you can probably just re-install Flynn using the `--clean` flag.
By the looks of it the bug can only happen on unclean shutdowns so if you avoid turning the machines off without properly shutting down `flynn-host` you should be right until we release a stable release that contains the fix.

**Comment by philiplb** [comment] 2016-03-04 10:29
Alright, thanks. :)

**Closed** 2016-03-04 13:38 UTC
