### ISSUE TITLE
Error running flynn install

### ISSUE THREAD

**Issue by cmason** [flynn/flynn#1589] opened 2015-06-11 13:25 UTC
When running `flynn install` on OSX I get the following error.
I'm using flynn v20150610.0.

```
$ flynn install
panic: CREATE INDEX: column ID already has an index: xID [recovered]
	panic: CREATE INDEX: column ID already has an index: xID

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0x208fceed0, 0x0, 0x0, 0x0, 0x7351e0, 0x209058e70)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/pkg/shutdown/handler.go:65 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/installer.NewInstaller(0x2208fa70c8, 0x2090703c0, 0x0)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/installer/installer.go:38 +0x1da
github.com/flynn/flynn/installer.ServeHTTP(0x0, 0x0)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/installer/http.go:49 +0x85
main.runInstaller(0x2090703a0, 0x0, 0x0)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/cli/install.go:21 +0x31
main.runCommand(0x7fff5fbff9ee, 0x7, 0xe62528, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/cli/main.go:180 +0xb7d
main.main()
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/cli/main.go:117 +0xd1a

goroutine 5 [syscall]:
os/signal.loop()
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0x208fceed0)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/pkg/shutdown/handler.go:54 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 11 [chan receive]:
database/sql.(*DB).connectionOpener(0x208ffbf40)
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/util/_toolchain/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/tmp/tmp.yHkfsRARoz/src/github.com/flynn/flynn/util/_toolchain/go/src/database/sql/sql.go:452 +0x31c
```

**Comment by jvatic** [comment] 2015-06-11 13:59
Is this your first time running `flynn install` on this machine? If you don't mind loosing data from previous installs, you could delete `~/.flynn/installer/data.db` which should get the installer into a working state. I able unable to reproduce the issue.

**Comment by cmason** [comment] 2015-06-11 14:22
Yes, this is a first time install. I deleted `~/.flynn` and reran `flynn install` and encountered the same error. After only removing `~/.flynn/installer/data.db` and rerunning, the installer is up and running. :clap: Thank you!

**Comment by jvatic** [comment] 2015-06-11 14:52
I'm glad it's working for you now! It's not clear what could have caused this, I'll close the issue for now and it can be reopened if it reoccurs.

**Closed by jvatic** 2015-06-11 14:52 UTC
Labels: bug, installer

**Comment by jdbetfair** [comment] 2015-06-23 02:14
FYI I experienced the same issue and fixed/worked around it with the same action.

**Comment by kelvin22** [comment] 2015-07-24 07:12
Same issue, deleted entire ~/.flynn folder and it worked.
First time installing on system, v20150724.0
