### ISSUE TITLE
CPU pegged at 100% on all cluster servers when builds are interrupted

### ISSUE THREAD

**Issue by kenaniah** [flynn/flynn#3161] opened 2016-07-20 22:11 UTC
## Description

Tested on various clusters from `v20160623.0` to `v20160719.0`...

When performing a build via `git push flynn` and interrupting it build via `Ctrl+C`, the `SIGINT` is apparently not trapped correctly by the slugbuilder.

Attempting to push and interrupt the same build multiple times in succession will cause all servers in the cluster to hang with the CPU pegged at 100% usage, leaving the cluster completely inoperable and unrecoverable. 

## Steps to reproduce

`git push flynn`

Wait for slugbuilder to start...

Send `SIGINT` (via `Ctrl+C` for most terminals) once the build is in progress

Repeat a few times until the build system fails with:

```
remote: ERROR: Build failed: ratelimited: maximum concurrent AddJob calls running, try again later
```

**Comment by rikur** [comment] 2016-07-21 01:03
+1 we got hit by this too. @titanous mentioned that he wanted to replace the ruby script that parses the Procfile with a Go implementation -- that should fix it. At least in my case it was a runaway Ruby process that ate up all the CPU.

**Comment by titanous** [comment] 2016-07-21 01:04
What buildpack are you using? Is this specific to a certain app or buildpack?

**Comment by rikur** [comment] 2016-07-21 01:05
I was using a PHP buildpack and yet it was a defunct ruby process that brought the server down.

**Comment by titanous** [comment] 2016-07-21 01:07
@rikur Did you also cancel a build to trigger this?

**Comment by kenaniah** [comment] 2016-07-21 01:08
For the record, I was using multipack, which loaded both
```
https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/heroku/heroku-buildpack-ruby
```

**Comment by titanous** [comment] 2016-07-21 01:14
So far I've been unable to reproduce this. Is there a specific phase of the deploy where cancelling it triggers the problem? Were you able to collect logs from the cluster after this happened?

**Comment by titanous** [comment] 2016-07-21 01:16
Also, do you know what process was pegging the CPU?

**Comment by kenaniah** [comment] 2016-07-21 01:23
I usually cancel immediately after the `-----> Building app_name...` part.

The servers are completely resource-constrained, so I can't collect logs, SSH, use the Flynn API, or do anything with them. 

It also might be interesting to note that in my case the git repo is roughly 385MB in size.

**Comment by titanous** [comment] 2016-07-21 01:24
Ahhh. That makes more sense. Are you on AWS? Have you moved blobs to S3?

**Comment by titanous** [comment] 2016-07-21 01:26
Also, did the issue resolve itself after waiting some period of time?

**Comment by kenaniah** [comment] 2016-07-21 01:28
AWS, but blobs are not moved to S3. 6 hours in and the CPUs are still pegged.

How does that make sense and how do I move the blobs (and what does that accomplish)?

**Comment by titanous** [comment] 2016-07-21 01:30
Blobs (git repos, compiled apps) are stored in Postgres by default, but you can use S3 instead. Here's a tutorial on how to do that: https://philiplb.de/flynn/2016/06/26/flynn-s3-blobstore/

We'll look into this issue, thanks for providing details.

**Comment by kenaniah** [comment] 2016-07-21 01:34
@titanous Please add that info directly to the Flynn docs. Seems like that's a very critical step that should happen during cluster setup.

**Comment by titanous** [comment] 2016-07-21 01:34
Yep, we will.

**Comment by titanous** [comment] 2016-07-21 02:31
I'm pretty sure that one contributing factor is that we persist the git repo archive back to the blobstore even if the push is cancelled/fails. I will fix that.

However, there is something else going on, as the cluster should not remain pegged. I wonder if a kernel or ZFS bug is being hit as well, because just persisting the repo blob should not cause a permanent problem. @josephglanville Any ideas?

@kenaniah Did you using the `flynn install` command to install on AWS, or did you manually install using a script? If you manually installed, what kernel version are you using?

**Comment by kenaniah** [comment] 2016-07-21 02:43
I did a manual install using one of the base images that Flynn used back in the day.

### My launch config:
```bash
#!/bin/bash
export FLYNN_VERSION=v20160718.0
sudo FLYNN_VERSION=v20160718.0 bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
sudo flynn-host init --discovery https://discovery.flynn.io/clusters/...
sudo start flynn-host
```

### My base AMI:

```
ami-06116566
```

Which is in `us-west-1` and is named:

```
ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160114.5
```

**Comment by titanous** [comment] 2016-07-21 02:44
Okay, and you didn't update the kernel at all? I'm leaning towards a kernel bug here. Please try with the `linux-generic-lts-xenial` kernel package.

**Comment by titanous** [comment] 2016-08-01 15:10
Closing due to a lack of information, please let us know if you are able to reproduce this with a newer kernel.

**Closed by titanous** 2016-08-01 15:10 UTC
