### ISSUE TITLE
Flynn - can not sync files - this is normal ?

### ISSUE THREAD

**Issue by pinkencryption** [flynn/flynn#3215] opened 2016-08-03 09:00 UTC
Hi,

We have a php app that stores data in a file. When we run this every time we hit we go to a different container. This also shows us different information each time on this page.

Now please compare this if we host a wordpress application and someone installs plugin on this app. We would not see the plugins on other running containers.

Can you please help me so I can understand flynn more or make sure it works as expected.

**Comment by pinkencryption** [comment] 2016-08-03 09:10
In this manner it seems we can not use flynn for anything that changes files on runtime. And that is a huge turndown for me.

**Comment by kwando** [comment] 2016-08-03 09:18
AFAIK shared and persistent volumes is not yet available in flynn. I think there are development efforts to get this functionality into flynn.

See #1681 and #1521

**Comment by IsNull** [comment] 2016-08-03 09:56
In a high available / scalable architecture you want your instances to scale. If you scale your instances (=running containers) you can not use container local file storage, since each instance would then have another state.

So what you are usually are doing is to move the persistent files out of the container and access the data over the network. This are usually databases or object stores such as S3. By using this approach, all your instances share the database or object store and thus have the same state.

Persistence is probably the most annoying part in the world of containers - because containers are not designed to solve the persistence issue.

**Comment by lmars** [comment] 2016-08-03 12:04
@pinkencryption NFS support is on our upcoming roadmap (#1521) and would allow you to share files between jobs.

As for Wordpress plugins, could you not deploy them alongside your app rather than storing them untracked on the filesystem?

**Comment by lmars** [comment] 2016-08-03 12:15
@pinkencryption for Wordpress, there is advice [here](https://github.com/mhoofman/wordpress-heroku#usage) for running on Heroku which does not have local file persistence.

**Comment by pinkencryption** [comment] 2016-08-03 17:09
@imars We thought over it and felt that above suggestion won't work. Plugins sometimes makes tables and add data as well. If we just add a plugin in another environment like DEV running with scale 1 and automatically pull and push changes from this it can break the data layer since databases for PROD and DEV would be diff. A plugin making changes in tables needs similar changes in DB to be pushed too and there would be no way to merge such changes without knowing explicitly what SQLs ran for the plugin. It is not just about wordpress, I wanted to use flynn for all the apps out there.  We can not control logic for it.

**Comment by pinkencryption** [comment] 2016-08-03 17:54
Also, can NFS really solve these issues? what will happen in case of concurrent writes.

**Comment by titanous** [comment] 2016-08-03 18:18
@pinkencryption I'm not sure what you're asking. Why would you concurrently write to the same file? NFS doesn't seem to have anything to do with ths.

**Comment by pinkencryption** [comment] 2016-08-03 18:27
@titanous If you consider how can you run something like wordpress / magento on flynn you will understand that. I am not saying this is not a big problem, all I am saying is I am trying to understand what flynn can do and what not. and will in future NFS support can solve me these situations.

**Comment by pinkencryption** [comment] 2016-08-03 18:28
Concurrent write to same files will inevitably occur, for instance - log files made by 100's of CMS out there.

**Comment by lmars** [comment] 2016-08-04 00:29
@pinkencryption 

> Plugins sometimes makes tables and add data as well

So I am totally unfamiliar with Wordpress, but a common way of handling this is to also check in any schema changes to source control so on deployment you can handle migrating your database accordingly, does Wordpress support anything like this?

> can NFS really solve these issues? what will happen in case of concurrent writes.

I was under the assumption you were talking about things like image uploads, which would be handled by a single job (from a single client) and most probably have uuid style filenames to avoid clashing with uploads from other jobs.

If however you know that multiple processes are going to try writing to the same file, then you need to use some form of synchronisation to serialise the writes if that is going to cause an issue.

> Concurrent write to same files will inevitably occur, for instance - log files made by 100's of CMS out there.

Why would multiple jobs need to share the same log file?

I am just trying to understand what you would want Flynn to do under these circumstances, any examples of how these apps work in a distributed fashion in other systems would be helpful :smile:

**Comment by pinkencryption** [comment] 2016-08-04 06:14
@Imars : 

Wordpress plugins would not support schema controls like that. If it can be implemented on db side somehow, than it is fine. But that is not likely to help.

Consider a plugin allowing people to upload files and share their videos. We have this running on flynn. Since its wordpress plugin is creating filenames, adding them to database but files are actually uploaded on disk. Therefore the UI's will start showing up the files as uploaded but they are scattered now on random containers. In practice a lot of the visitors of website will not see a lot of files since the container they are attached too would not have those files locally.

For this to work the entire app has to be designed in a docker friendly way - and making sure no local data is present.

Also - I see that everytime we submit something it may reference a diff containers. Can it also cause issue with session, states, and something like streaming apps ?

**Comment by hbjohnnash** [comment] 2016-08-04 06:38
And as for several jobs writing to same log file I would assume he was actually referring to a case where same log file is getting used for registering exceptions and errors that occur during any request.
Like in Magento we have two log files exception.log and system.log which contain all the exceptions and errors, appended to them, that are caused by the code when a certain request is made. 
For every request exception and error info is simply appended to these files.. 
And then in case these files are not in sync, debugging any issue would become really confusing, as these files would be different on different scaled up containers depending upon whichever container was used during a request.
Hope, it makes sense.

**Comment by IsNull** [comment] 2016-08-04 06:56
>For this to work the entire app has to be designed in a docker friendly way - and making sure no local data is present.

>Also - I see that everytime we submit something it may reference a diff containers. Can it also cause issue with session, states, and something like streaming apps ?

You pretty much cut it right to the chase of the matter. An application needs to follow quite some core principles that it can work in the _cloud_ (meaning ready for container scaling). [12factor.net](http://12factor.net)

The most important (or actually, the hardest part if it is an existing code base) is to ensure your backend is **stateless**. This means no sessions, no local files etc.

One tricky part to get stateless is authentication, since depending on your architecture (especially Microservice architecture) you might even have multiple services which talk to each other behind the scene. There Json Web Tokens (JWT) might be an elegant way to get things done stateless.

**Comment by titanous** [comment] 2016-08-04 13:29
> And then in case these files are not in sync, debugging any issue would become really confusing, as these files would be different on different scaled up containers depending upon whichever container was used during a request.

Logs should be printed to stderr/stdout, which will allow you to see all logs in a single stream.

I'm going to close this issue. We already have issues for improvements to handle sharing files between containers.

**Closed by titanous** 2016-08-04 13:29 UTC
