### ISSUE TITLE
Flynn does not recognize my ruby version from my Gemfile

### ISSUE THREAD

**Issue by carlminden** [flynn/flynn#2929] opened 2016-06-14 23:30 UTC
I have a ruby on rails app I am trying to deploy to a flynn cluster I just set up, at the top of my Gemfile i have

```
source 'https://rubygems.org'

ruby "2.1.2"

gem 'rails', '4.0.4'
```

followed by the various gems I require

When I try to deploy this i get the following at the top of the deployment:

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.4
```

bundler then proceeds to fail because it tries to install eventmachine 1.0.3 because it is not supported on ruby 2.2. I suppose I could try to update my requirements to work with ruby 2.2, but I feel like I should be able to get flynn to use whichever ruby version I ask it to.

I am fairly sure I am specifying my ruby version as described by the ruby deployment docs here: https://flynn.io/docs/how-to-deploy-ruby

Am I missing something?

**Comment by titanous** [comment] 2016-06-14 23:32
Did you run `bundle` and commit the updated `Gemfile.lock` after setting the Ruby version?

**Comment by carlminden** [comment] 2016-06-14 23:39
yes, but I dont see anything in the Gemfile.lock that mentions my ruby version, it seems to only have information about gems

**Comment by titanous** [comment] 2016-06-14 23:41
Yeah, I just wanted to double-check. Try changing the Ruby version to `2.1.10`, this is in theory the only version in the 2.1 series supported by the buildpack.

**Comment by carlminden** [comment] 2016-06-14 23:48
Nope, it still says "Using Ruby version: ruby-2.2.4" with the Gemfile set to use ruby 2.1.10

**Comment by titanous** [comment] 2016-06-14 23:50
Okay, please try running:

```text
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby
```

And then deploying again. If that doesn't work I will investigate in detail, it may be an upstream bug in the buildpack.

**Comment by carlminden** [comment] 2016-06-14 23:52
The only difference that seems to have made is that the deploy says "-----> Fetching custom buildpack" before continuing on to detect Ruby/Rails and then use ruby 2.2.4

**Comment by titanous** [comment] 2016-06-14 23:52
Okay, I will investigate. Please create a gist with the entire Gemfile if possible.

**Comment by titanous** [comment] 2016-06-14 23:53
(and the Gemfile.lock)

**Comment by carlminden** [comment] 2016-06-14 23:56
Gemfile: https://gist.github.com/carlminden/f44d70dac5ba4ebdf2011b6ad2b24d1e
Gemfile.lock: https://gist.github.com/carlminden/d4873b096d73c4f3b0c4a2b11b435034

Thanks.

**Comment by titanous** [comment] 2016-06-15 14:46
I was unable to reproduce this with the development version of Flynn, the files you provided bundled correctly with ruby 2.1.10. I would suggest creating a new app and deploying again, it's possible that the buildpack has aggressively cached something. Let me know if it's still not working for you.

**Comment by carlminden** [comment] 2016-06-15 14:50
I deleted the app, recreated it and then pushed the code to deploy again and am still experiencing the same behavior of it detecting ruby 2.2.4

**Comment by carlminden** [comment] 2016-06-15 14:51
could it be something to do with the configuration of my flynn servers? do I need to go into them and make sure they have more ruby versions installed or something?

**Comment by titanous** [comment] 2016-06-15 14:52
You shouldn't need to change anything on the servers. Are you certain that the changes to the `Gemfile` have been committed and are being pushed? I get this error when I change to an unsupported version:

```text
       Your Ruby version is 2.1.10, but your Gemfile specified 2.1.9
       Bundler Output: Your Ruby version is 2.1.10, but your Gemfile specified 2.1.9
       !
       !     Failed to install gems via Bundler.
       !
```

**Comment by carlminden** [comment] 2016-06-15 15:00
ok, i figured it out...it was all my fault I was on a non-master branch and just repeatedly pushing an unchanged master to flynn...i am sorry for wasting your time :)

**Comment by titanous** [comment] 2016-06-15 15:00
No problem, have a good day!

**Closed by titanous** 2016-06-15 15:00 UTC
