### ISSUE TITLE
Dramatic increase in network cross-talk after 2016-07-11

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3343] opened 2016-08-29 23:41 UTC
Starting when I rebuilt all our clusters on 2016-07-11, we have experienced an order of magnitude growth in network traffic costs for AWS. I'm not certain if this started on v20160711.0, or some nearby prior version: our easily accessible logs don't go back that far. Prior to that time, traffic costs are pretty steady and low; afterward, they leap up, and continue to grow slowly as time goes on, until a cluster rebuild resets them to near the initial (high) value.

On a hunch caused by variance between our QA and Production deployments, I moved all clusters to live in a single AWS AZ, on 08-27. That has reduced the traffic costs down to negligible levels (even lower than prior to the incident), lending credence to the theory that this is cross-talk we are being charged for. 

http://i.imgur.com/68UMqrB.png is the graph of our Flynn traffic costs since July, and http://i.imgur.com/Tdc4Kt3.png the traffic over the last 6 days.

**Comment by titanous** [comment] 2016-08-30 19:30
Are you using the S3 blobstore backend? If not, this could be database replication traffic.

**Comment by temujin9** [comment] 2016-08-30 20:10
We are not using it yet. Do you have an explanation for why it shot up on the 11th?

**Comment by titanous** [comment] 2016-08-30 23:05
Postgres 9.5 was merged in on July 6 (#2952). I'm not aware of anything related to this, but it's possible that there was a change in the way replication works that increased traffic.

We also changed the job restart algorithm to not back off nearly as aggressively (#3082), so if you had jobs that are consistently crashing, this would result in traffic downloading slugs for each attempt as there is currently no caching (this will be fixed by #3100).

**Comment by titanous** [comment] 2016-08-30 23:08
If the backoff algorithm is the cause, switching to the S3 blobstore backend would reduce these costs to zero, or you could track down the crashing apps and fix them.

**Comment by titanous** [comment] 2016-09-22 22:27
@temujin9 Is this still an issue?

**Comment by temujin9** [comment] 2016-09-26 03:31
I suspect so, but we've moved to single-AZ for the time being, and I'm in the middle of a very different set of tests, so I can't say with certainty.

I'll put it on my list to test after migration.

**Comment by titanous** [comment] 2016-11-07 19:41
I'm closing this as we now cache slug artifacts on each host (#3619).

**Closed by titanous** 2016-11-07 19:41 UTC

**Comment by lmars** [comment] 2016-11-16 18:16
FYI another factor here is each scheduler in the cluster syncing jobs from each host in the cluster every 30s.

Each job tends to be around 2.5KB when serialized, so if you have say 50,000 jobs then that is ~125MB being transferred between each host every 30s.

I am working on adding a ceiling to the number of jobs in the host state database.
