### ISSUE TITLE
Flynn install fail and chrome browser hangs

### ISSUE THREAD

**Issue by ict4ngo** [flynn/flynn#2125] opened 2015-11-12 00:59 UTC
Running Ubuntu 14.04 when running flynn install it opens a browser than show the following error and hang there

flynn install
Open http://localhost:51343 in your browser to continue.
[21338:21338:1111/195522:ERROR:url_pattern_set.cc(240)] Invalid url pattern: chrome://print/*
[21338:21559:1111/195532:ERROR:get_updates_processor.cc(243)] PostClientToServerMessage() failed during GetUpdates
[21338:21338:1111/195537:ERROR:extension_downloader.cc(695)] Invalid URL: '' for extension lklieeaongcaklpejdodbkcmbdfpdabj
[21338:21366:1111/195538:ERROR:connection.cc(1060)] Web sqlite error 1555, errno 0: UNIQUE constraint failed: autofill.name, autofill.value, sql: INSERT INTO autofill (name, value, value_lower, date_created, date_last_used, count) VALUES (?, ?, ?, ?, ?, ?)
[21338:21366:1111/195538:ERROR:autocomplete_syncable_service.cc(138)] Autofill datatype error was encountered: Failed to update webdata.

**Comment by titanous** [comment] 2015-11-12 02:13
I assume this is with Chrome on Ubuntu? What method did you use to install Chrome?

**Comment by NeilW** [comment] 2015-11-12 08:11
Same on 12:04 with Chromium Browser. All via packages.

$ flynn install
Open http://localhost:60929 in your browser to continue.
[4545:4545:1112/080829:ERROR:nss_util.cc(845)] After loading Root Certs, loaded==false: NSS error code: -8018
libGL error: MESA-LOADER: could not create udev device for fd 26
ATTENTION: default value of option force_s3tc_enable overridden by environment.

**Comment by NeilW** [comment] 2015-11-12 08:37
Additionally nothing from the server: 

```
$ telnet localhost 60929
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
get /
```

**Comment by ict4ngo** [comment] 2015-11-12 14:15
that's exactly the issue, although I mainly use firefox, it was only firing up chrome, the workaround is to fix the issue with "which" browser that is started. Why a browser would block the installation is beyond me  though.

**Comment by titanous** [comment] 2015-11-15 16:41
@jvatic please look into this.

**Comment by jvatic** [comment] 2015-11-16 02:36
I've managed to reproduce with both Google Chrome and Chromium (Ubuntu 14.04) only when the respective browser is not already running. Closing the hung browser allows opening the link elsewhere.

The package the installer uses to launch the browser [attempts `sensible-browser`, falling back to `xdg-open`](https://github.com/flynn/flynn/blob/cadf0a3ecc249fd888068b3fb7409b83371181a9/Godeps/_workspace/src/github.com/pkg/browser/browser_linux.go). The former appears to always use Google Chrome if it's installed, and the latter uses the default browser. When using the latter program (make the former unavailable) this issue doesn't appear to be present.

@ict4ngo @NeilW Please confirm removing `sensible-browser` (`sudo mv "$(which sensible-browser)" "$(which sensible-browser)-bak"`) bypasses the issue.

**Comment by NeilW** [comment] 2015-11-16 08:23
Confirmed.

`sensible-browser` is a simple shell script that execs the current selected browser. You can change which browser by running `sudo update-alternatives --config gnome-www-browser`

You get the same problem with Firefox.

The problem is straightforward. `browser.OpenURL` is buggy. `sensible-browser` is a serial application that will block the current process due to the Wait in `os.exec.Run` - unlike 'open' or 'xdg-open'. 

It also uses the system-wide browser default rather than the user selected default in the UI.

The launch should use 'xdg-open' only to get the user selected browser. 'xdg-open' falls back to the 'sensible-browser' code anyway (it looks for the program 'x-www-browser').

'xdg-open' does the right thing and forks the browser so that the Wait in `os.exec.Run` doesn't block. 

See https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/562476 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539191 for reasons why launching `sensible-browser` is the wrong approach.

**Comment by jvatic** [comment] 2015-11-16 18:24
@NeilW Thanks! I agree the installer should exec `xdg-open` and not attempt `sensible-browser`.

**Closed** 2015-11-17 01:14 UTC
Labels: bug, installer
