### ISSUE TITLE
dashboard: Stuck on install cert

### ISSUE THREAD

**Issue by SolarisYan** [flynn/flynn#2502] opened 2016-02-29 08:00 UTC
when i login in the dashbord,it always show this 
Install CA certificate to continue?
but i have installed the flynn-ca.cer.
how should i do，any one can help me?

**Comment by SolarisYan** [comment] 2016-02-29 08:02
like this: ![image](https://cloud.githubusercontent.com/assets/8148762/13388747/b382f5c4-defd-11e5-92c7-2fc9283544a0.png)

**Comment by jvatic** [comment] 2016-02-29 08:53
@SolarisYan What browser and version of Windows are you using?

**Comment by SolarisYan** [comment] 2016-02-29 10:00
@jvatic i use win 10 and the browser is chrome,but i change the firefox all is ok,thx

**Comment by jvatic** [comment] 2016-02-29 10:18
@SolarisYan Did you try restarting Chrome after installing the cert?

**Comment by SolarisYan** [comment] 2016-03-01 01:24
@jvatic ofcoure i restart it,now the issue is like follow:
![qq 20160229184654](https://cloud.githubusercontent.com/assets/8148762/13414593/f6374776-df8e-11e5-8071-316eb4cd5b65.png)

and the same to IE

**Comment by jvatic** [comment] 2016-03-01 14:57
@SolarisYan try going to http://dashboard.demo.flynn.com instead of https.

**Comment by dottodot** [comment] 2016-03-04 11:32
I have the same problem after successfully installing the cert on one machine I've tried to install on another and now can't get past the install cert page. The http:// version loads but doesn't show any apps.

**Comment by jvatic** [comment] 2016-03-12 01:32
I am unable to reproduce this. Please make sure you're following the installation steps exactly for the certificate (and that there aren't any security exceptions created for it in your browser).

**Comment by jvatic** [comment] 2016-03-13 14:50
Closing this issue for now. Please open a new issue with the browser/version OS/version and steps to reproduce if encountered again.

**Closed by jvatic** 2016-03-13 14:50 UTC
Labels: bug, dashboard
