### ISSUE TITLE
CLISuite.TestPs: timed out waiting for scale events

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1329] opened 2015-03-22 02:28 UTC
```
FAIL: test_cli.go:174: CLISuite.TestPs

++ 02:20:51.367 created app shrews-capture-latchford (2446b3e2b3e040c7b603273f67b6a69e)
++ 02:20:51.441 /home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn -a shrews-capture-latchford ps
ID  TYPE

++ 02:20:51.486 /home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn -a shrews-capture-latchford scale echoer=3
scaling echoer: 0=>3

02:20:54.601 ==> echoer dcc5935e-99ce4080b31a40cfbcdd423fef8a31c7 up
02:20:55.761 ==> echoer dcc5935e-30f2ba9112cc465896573bd7fed136c4 up
timed out waiting for scale events

test_cli.go:184:
    t.Assert(app.flynn("scale", "echoer=3"), Succeeds)
... result *main.CmdResult = &main.CmdResult{Cmd:[]string{"/home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn", "-a", "shrews-capture-latchford", "scale", "echoer=3"}, Output:"scaling echoer: 0=>3\n\n02:20:54.601 ==> echoer dcc5935e-99ce4080b31a40cfbcdd423fef8a31c7 up\n02:20:55.761 ==> echoer dcc5935e-30f2ba9112cc465896573bd7fed136c4 up\ntimed out waiting for scale events\n", Err:(*exec.ExitError)(0xc20803b218)}
```

https://ci.flynn.io/builds/20150322021041-b34029e3

**Comment by lmars** [comment] 2015-03-22 12:24
Duplicate of #907.

**Closed by lmars** 2015-03-22 12:24 UTC
Labels: bug, ci-flake
