### ISSUE TITLE
Can't set env on broken deployment

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2525] opened 2016-03-04 16:50 UTC
I've push a deployment but have some wrong env variable which are causing the app not to work but using `timed out waiting for deployment completion` give an error of 

> timed out waiting for deployment completion

before I had pushed the app I could set envs without any issue

**Comment by titanous** [comment] 2016-03-13 16:42
Would you please provide detailed reproduction steps with an open source example app? I am so far unable to reproduce this.

**Comment by titanous** [comment] 2016-03-15 03:01
Closing for lack of detail, please open a new issue with reproduction steps.

**Closed by titanous** 2016-03-15 03:01 UTC
