### ISSUE TITLE
Second push fails

### ISSUE THREAD

**Issue by kenaniah** [flynn/flynn#3177] opened 2016-07-25 05:53 UTC
Just ran into the same issue as #1934 today. Git push then interrupt then git push again produces the following issue:
```
-----> Discovering process types
       Procfile declares types -> web
       Default process types for Multipack -> rake, console, web
-----> Compiled slug size is 61M
-----> Creating release...
remote: ERROR: Error deploying app release: validation_error: Requested formation includes process types that do not exist in release. Invalid process types: [web]
```

Cluster is running `v20160722.1`.

**Comment by titanous** [comment] 2016-07-25 11:52
I am unable to reproduce this. Can you provide a repo that demonstrates the issue?

**Comment by titanous** [comment] 2016-08-01 15:11
Closing due to a lack of information, please let us know if you can provide information on how to reproduce the error.

**Closed by titanous** 2016-08-01 15:11 UTC
