### ISSUE TITLE
pinkerton cleanup "device or resource busy" 

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#38] opened 2014-08-07 22:52 UTC
Sometimes when running `pinkerton cleanup` from the libvirt backend, it fails with this error:

```text
context.go:90: rename /var/lib/docker/aufs/mnt/tmp-flynn-discoverd-277ab3fe3b594e80ad1d40838c2f7b66 /var/lib/docker/aufs/mnt/tmp-flynn-discoverd-277ab3fe3b594e80ad1d40838c2f7b66-removing: device or resource busy
```

**Comment by lmars** [comment] 2015-06-03 00:25
As discussed in #1125, the underlying issue here is that `libvirt_lxc` processes [clone the mount namespace](https://github.com/c4milo/libvirt/blob/v1.2.2/src/lxc/lxc_controller.c#L1906) which then stops the rootfs of previous jobs being removed (because it is still mounted in some child namespaces).

Failing to cleanup when a job dies leads to wasted disk space (mainly by directories in `/var/lib/docker/aufs/diff`), which is causing issues for some users (e.g. #1565), so here is a script to manually clean the old jobs:

https://gist.github.com/lmars/6d072bc88c3a4c9f87d2

FYI this would not be an issue if we switched to `libcontainer` as it [performs a pivot_root and subsequently detaches all the host mounts](https://github.com/docker/libcontainer/blob/master/rootfs_linux.go#L369-L393).

**Comment by temujin9** [comment] 2015-06-03 16:32
Running the script to manually clean jobs results in a large number of `cannot remove [...] : Directory not empty` and `cannot remove [...] : Device or resource busy` results. Is that expected behavior?

**Comment by lmars** [comment] 2015-06-05 14:44
@temujin9 seeing `cannot remove [...] : Directory not empty` seems odd as the script uses `rm -rf`, does this happen for both `mnt` and `diff` directories?

For the `Device or resource busy` errors, can you do a grep in both `proc/mounts` and `/proc/*/mounts` for the directory to see where it is still mounted (and which processes have it mounted)?

**Comment by temujin9** [comment] 2015-06-05 17:09
https://gist.github.com/temujin9/10bd459af41c3887a289 has the full results of a run, and the grep results you requested.

**Comment by titanous** [comment] 2015-07-05 00:54
This issue looks like a straight-up race. We start cleanup before the container has stopped (it starts when we receive a signal from the containerinit process). I'll fix this up.

**Comment by temujin9** [comment] 2015-08-17 16:28
@titanous Do you believe this is fixed? If so, I'll test removing my cleanup patch locally.

**Comment by titanous** [comment] 2015-08-17 16:29
@temujin9 I think so, more data points would be great.

**Comment by temujin9** [comment] 2015-08-27 19:28
@titanous This does not appear to be fixed; several of my clusters disks are filling up rapidly.

**Comment by titanous** [comment] 2015-08-27 20:27
@temujin9 Thanks! I'll work on a fix.

**Comment by temujin9** [comment] 2015-08-28 14:07
https://gist.github.com/75d7cdc8fd81c7f48de6 is the latest example, in case it helps.

**Comment by titanous** [comment] 2015-10-15 17:03
This is apparently still not fixed: https://gist.github.com/anonymous/b19fb1d5d8ab23028e29#file-upstart-flynn-host-log-L214-L215

**Comment by temujin9** [comment] 2016-02-01 19:09
Now that I've switched #2063 on, should I expect this to be worked around? If so, I'll remove my patch.

**Comment by titanous** [comment] 2016-02-01 19:15
I'm not sure they were related. New data points would be helpful, but it looks like I spotted this on CI after my last attempted fix.

**Comment by temujin9** [comment] 2016-02-01 20:35
You did appear to switch from AUFS to VFS with that, so I'm hopeful. I'll try it once I've landed the backups code.

**Closed** 2016-07-10 23:24 UTC
Labels: bug, pinkerton, upstream/docker
