### ISSUE TITLE
Allow distribution of jobs between hosts in different zones

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#3363] opened 2016-09-06 17:18 UTC
There should be a mechanism where hosts which are tagged as belonging to the same zone can be selected against when distributing jobs (or job types) that are already present in that zone.

These zones could represent anything from datacentres, to groups of machines on the same rack, switch, or power bus. These tags will need to be designated as zone tags.

**Comment by lmars** [comment] 2016-09-07 00:28
Duplicate of #3126.

**Closed by lmars** 2016-09-07 00:28 UTC
