### ISSUE TITLE
deployer: Allow jobs serving HTTP clients to shutdown gracefully

### ISSUE THREAD

**Issue by archSeer** [flynn/flynn#966] opened 2015-02-08 10:13 UTC
Continuing off of the discussion in https://github.com/flynn/flynn/pull/848#issuecomment-72989252, in order to achieve true zero-downtime, we'll need to ensure that pending requests (ignoring long-running requests) get fulfilled before we terminate the job.

Once this issue is resolved, #848 can be reopened and merged (it passes right now, but it's racy)

**Comment by lmars** [comment] 2015-02-09 02:22
A possible approach:

* deployer sends SIGUSR1 to job which unregisters from discoverd
* router notices unregister and kills any idle keep-alive connections to backend
* router has API endpoint exposing active HTTP connections for a given backend (possibly an event stream)
* deployer waits for active HTTP connections to drop to zero then kills job (with a sane timeout)

See [discussion in IRC](https://botbot.me/freenode/flynn/2015-02-09/?msg=31558808&page=1).

**Comment by titanous** [comment] 2015-02-09 02:24
@bgentry @benburkert What do you think of the feasibility/sanity of @lmars proposal?

**Comment by bgentry** [comment] 2015-02-09 02:33
> * router notices unregister and kills any idle keep-alive connections to backend

The only API exposed by `http.Transport` is to let us close *all* idle conns: http://golang.org/pkg/net/http/#Transport.CloseIdleConnections

That means we'd have to close all idle conns to all backends, or else have different `Transports` for each backend or at least each service.

> * router has API endpoint exposing active HTTP connections for a given backend (possibly an event stream)

I don't think this will ever be doable unless we fully move away from `http.Transport` and do all of our own connection management. That'd be a very large undertaking.

Also, what about websockets or any other upgraded conns? How should those be handled on a deploy?

**Comment by titanous** [comment] 2015-02-09 02:51
> I don't think this will ever be doable unless we fully move away from http.Transport and do all of our own connection management. That'd be a very large undertaking.

> Also, what about websockets or any other upgraded conns? How should those be handled on a deploy?

It seems like all of this could be solved by tracking connections returned from a custom dialer?

**Comment by bgentry** [comment] 2015-02-09 17:42
@titanous hmm yeah interesting idea. You could have a dialer that tracks conns opened to a particular `host:port`, and then offers the ability to close those conns. A couple of issues with that come to mind:

1. The dialer would have no way to know when those conns have been closed for other reasons, and would thus keep references to potentially closed conns indefinitely. To solve that, you'd have to also use your own `net.Conn` type that notifies the dialer when it has been closed (similar to how `CloseNotify()` works under the hood in `net/http`).
2. If conns are closed by anything other than the `http.Transport`, you will almost certainly run into problems caused by https://github.com/golang/go/issues/8946 on high-traffic sites. Which is to say that you'll see failed requests when those requests attempt to use a conn that's in the process of closing (or has just been closed)

**Comment by bgentry** [comment] 2015-02-09 18:07
Another approach might be to keep an `http.Transport` per backend, which would let us `CloseIdleConnections()` on just that particular backend. Probably a lot of memory overhead but not the worst choice :)

**Comment by benburkert** [comment] 2015-02-09 18:36
What is the importance of manually closing the idle connections to the backends? When the backend goes away, the host will close those TCP connections to the router anyways. The overhead of keeping track of those connections for a few extra seconds is pretty small.

**Comment by titanous** [comment] 2015-02-09 18:38
@benburkert Hmm, yeah, that's a good point.

**Comment by bgentry** [comment] 2015-02-09 18:42
Are you mostly interested in just ensuring that open requests to backends are allowed to finish?

If so, the backend gets unregistered from discoverd, which means that no new requests are going to get sent through to it. So at that point it's really up to the backend to decide if & when to clean up ongoing requests. Can't that be done by sending the backend process the proper signal?

The only problem that comes to mind is if the backend receives its signal before all routers have unregistered the backend (and thus might still send new requests to it). That seems like a simpler problem to deal with.

**Comment by bgentry** [comment] 2015-02-09 18:43
Also, in the scenario I just explained, the deployer doesn't necessarily need to wait for active HTTP requests to drop to zero. It can just wait for the backend process to exit.

**Comment by titanous** [comment] 2015-02-09 18:48
@bgentry Yes, that's the goal. The main thing I'm interested in investigating is whether every app needs to be capable of keeping track of live connections and only exiting when all are finished. It can be tricky to impossible to do this with arbitrary web frameworks and HTTP implementations, and it seems like it might be possible to do it at the platform level without much overhead and zero app modifications.

**Comment by titanous** [comment] 2015-02-09 18:49
Also, the keep-alive connections from the router will be confusing to some implementations.

**Comment by lmars** [comment] 2015-02-10 03:07
So it would be nice to close the idle keep-alive connections, but the main goal here is to not drop any HTTP requests by killing jobs too early.

In an ideal world the deployer would send `SIGTERM` to the job, and the job itself would wait for requests to finish before exiting, leaving the deployer to just wait for it to exit, but even the popular frameworks we currently support don't provide a consistent way of doing so (e.g. Ruby/Thin gracefully shuts down on `SIGTERM` / `SIGQUIT`, whereas PHP/Apache does so on `SIGWINCH`).

The deployer is likely going to use a timeout of ~10s, so if the router doesn't accurately track the active requests in all cases, at worst killing jobs will take upto 10s longer than necessary, but I don't think that is a major issue (unless the router tracking is quite inaccurate).

**Comment by lmars** [comment] 2016-11-13 20:41
This was implemented for short lived requests in #3421, and #3513 covers long lived requests.

**Closed by lmars** 2016-11-13 20:41 UTC
Labels: component/deployer, component/router, kind/enhancement
