### ISSUE TITLE
TImeout on deployments

### ISSUE THREAD

**Issue by monaka** [flynn/flynn#1659] opened 2015-07-13 02:00 UTC
My cluster becomes to return a timeout error always after few times deployment.
Is it degrade to #1015 ?

```
-----> Discovering process types
       Procfile declares types -> web, worker, rake, console, clock
       Default process types for Ruby -> rake, console, web, worker
-----> Compiled slug size is 39M
-----> Creating release...
remote: Error deploying app release: timed out waiting for deployment completion
To ssh://git@{{censored}}:2222/redmine.git
 ! [remote rejected] monami -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@{{censored}}:2222/redmine.git'
```

https://gist.github.com/8f5015fc463161f332cc
https://gist.github.com/8c0cccb8e46a2608fc38
https://gist.github.com/9640751c1a42a68ebdde

**Comment by titanous** [comment] 2015-07-13 14:31
It looks like the cause is etcd failure: https://gist.githubusercontent.com/anonymous/8f5015fc463161f332cc/raw/etcd-app-monaflynn3-2b9fda20957548849064dcb1f18688a6.log

As I said, there is work in progress to fix this.

**Comment by paul-e-cooley** [comment] 2015-08-04 15:11
Any word on when we can expect a fix for this issue? And is it somewhat random or predictive?

**Comment by titanous** [comment] 2015-08-04 15:20
@paul-e-cooley There are a few root causes for this error message, one is caused by network instability in multinode that causes etcd to fail (#1612 is the underlying change necessary to resolve this). I believe someone from your team also reported #1682 which appears to be slightly different, did it reoccur?

**Comment by paul-e-cooley** [comment] 2015-08-04 15:27
Yes. We are testing deployment automation and after a number of deploys to the flynn cluster, the error occurs and continues. Even setting environment variables at that point fails.

**Comment by titanous** [comment] 2015-08-04 15:29
@paul-e-cooley Okay, please post the cluster debug info and we'll look for the root cause.

**Comment by tianx2** [comment] 2015-08-04 15:54
@titanous here is the debug info - https://gist.github.com/c1492577d7e320868a5f

**Comment by tianx2** [comment] 2015-08-04 16:07
@titanous I currently don't have system metrics logging at the moment. I doubt that high load is causing this. However, I'll install system metrics logging (dd-agent from Datadog) today to have data to back up my claim.

**Comment by titanous** [comment] 2015-08-04 16:34
@tianx2 I'm also working on updating to etcd v2.1.1 which claims to fix some related issues and may improve the situation.

**Comment by titanous** [comment] 2015-09-09 16:29
Closing, as we no longer use etcd.

**Closed by titanous** 2015-09-09 16:29 UTC
Labels: P1
