### ISSUE TITLE
/status in dashboard is empty

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#3301] opened 2016-08-16 16:36 UTC
I think it's querying wrong URI. sends request to status.***.flynnhub.com without a key

**Comment by jvatic** [comment] 2016-08-16 16:40
This appears to be a duplicate of #2988.

`flynn -a dashboard env set STATUS_KEY=$(flynn -a status env get AUTH_KEY)`

**Closed by jvatic** 2016-08-16 16:40 UTC
