### ISSUE TITLE
future of Flynn

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#4244] opened 2017-09-13 09:27 UTC
Flynn is awesome and as a small startup, we built everything around it. it gave us the freedom to focus on other things. 

Flynn IRC support channel became so quiet. I no longer see as many activity in flynn github either. I rarely see any new features. I'm worried about the future of Flynn. is everything ok?

if Flynn closes shop, would you open source everything else so we can keep our clusters running?

I hope this is not the case

**Comment by titanous** [comment] 2017-09-13 15:06
This is a duplicate of #4242.

We still have a full-time team working on Flynn, and are financially stable. As I mentioned in the issue referenced above, our focus is on our paying customers since they are what allow us to continue building Flynn. The reason you may not see us as often in IRC is because most of our support time is spent in private Slack channels with our customers.

Everything you need to run Flynn forever without paying us anything is already free and open source in this repo. We have no closed source dependencies in the open source project, and that won't change.

**Closed by titanous** 2017-09-13 15:06 UTC
