### ISSUE TITLE
cli: Config not being updated after domain migration

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2514] opened 2016-03-02 13:09 UTC
We should be updating the local config after running a domain migration.

**Comment by jvatic** [comment] 2016-03-02 13:11
(Bug reported in IRC: https://botbot.me/freenode/flynn/2016-03-02/?msg=61360187)

**Comment by titanous** [comment] 2016-03-02 15:55
Duplicate of #2453.

**Closed by titanous** 2016-03-02 15:55 UTC
Labels: bug, cli
